import { randomUUID } from 'node:crypto';
import { Injectable, Optional } from '@nestjs/common';
import { SalesService } from '../sales/sales.service';
import { AccountingService } from '../accounting/accounting.service';
import { AccountingRepository } from '../accounting/accounting.repository';
import type { JobOrderRecord } from '../sales/sales.types';
import { FinanceNotFoundError, FinanceValidationError } from './finance.errors';
import { FinanceRepository } from './finance.repository';
import type {
  CollectionRecord,
  CreateCollectionInput,
  CreatePaymentInput,
  CreatePurchaseInvoiceInput,
  CreateRetentionInput,
  CreateSalesInvoiceInput,
  PaymentRecord,
  PurchaseInvoiceRecord,
  RetentionRecord,
  SalesInvoiceRecord,
} from './finance.types';

@Injectable()
export class FinanceService {
  constructor(
    private readonly repository: FinanceRepository,
    private readonly salesService: SalesService,
    @Optional() private readonly accountingService?: AccountingService,
    @Optional() private readonly accountingRepo?: AccountingRepository,
  ) {}

  private async getJobOrderOrThrow(jobOrderReference: string): Promise<JobOrderRecord> {
    const jobOrders = await this.salesService.getJobOrders();
    const found = jobOrders.find((jo) => jo.jobOrderNumber === jobOrderReference);
    if (!found) throw new FinanceNotFoundError(`job order "${jobOrderReference}" does not exist`);
    return found;
  }

  // --- Collections (Customer Inflow) ---
  async getCollections(jobOrderReference?: string): Promise<CollectionRecord[]> {
    return this.repository.listCollections(jobOrderReference);
  }

  async recordCollection(input: CreateCollectionInput): Promise<CollectionRecord> {
    const amount = Number(input.amount);
    if (!Number.isFinite(amount) || amount <= 0) throw new FinanceValidationError('amount must be positive');

    const jobOrder = await this.getJobOrderOrThrow(input.jobOrderReference);
    const sequence = (await this.repository.countCollections()) + 1;
    const year = new Date().getFullYear();
    const collectionNumber = `COL-${year}-${String(sequence).padStart(6, '0')}`;

    const collectionRecord = await this.repository.insertCollection({
      id: randomUUID(),
      collectionNumber,
      orgNodeId: jobOrder.orgNodeId,
      ...input,
    });

    // Automated Double-Entry Posting for Customer Collection:
    // [Dr: Bank/Cash (receivedInAccountId) / Cr: AR (Customer Subledger)]
    if (this.accountingService && this.accountingRepo && input.receivedInAccountId && jobOrder.orgNodeId) {
      const config = await this.accountingRepo.findCompanyConfig(jobOrder.orgNodeId);
      const determinations = await this.accountingRepo.listAccountDeterminations(jobOrder.orgNodeId);

      const arDet = determinations.find((d) => d.accountPurpose === 'receivable');
      const arAccountId = arDet?.accountId ?? config?.defaultReceivableAccountId;

      if (arAccountId) {
        const draftEntry = await this.accountingService.createEntry({
          orgNodeId: jobOrder.orgNodeId,
          description: `Customer Collection ${collectionNumber} for JO ${input.jobOrderReference}`,
          reference: collectionNumber,
          entryDate: input.collectionDate,
          isAutoGenerated: true,
          idempotencyKey: `collection-${collectionRecord.id}`,
          sourceEventType: 'collection',
          lines: [
            {
              accountId: input.receivedInAccountId,
              debitAmount: Number(input.amount).toFixed(4),
              creditAmount: '0',
              description: `[Auto] Deposit for Collection ${collectionNumber}`,
            },
            {
              accountId: arAccountId,
              debitAmount: '0',
              creditAmount: Number(input.amount).toFixed(4),
              description: `[Auto] AR Clearance for Collection ${collectionNumber}`,
              partyType: 'customer',
              partyId: jobOrder.customerId ?? undefined,
            } as any,
          ],
        });

        await this.accountingService.postEntry(draftEntry.id);
      }
    }

    return collectionRecord;
  }

  // --- Retentions ---
  async getRetentions(jobOrderReference?: string): Promise<RetentionRecord[]> {
    return this.repository.listRetentions(jobOrderReference);
  }

  async createRetention(input: CreateRetentionInput): Promise<RetentionRecord> {
    const amount = Number(input.originalAmount);
    if (!Number.isFinite(amount) || amount <= 0) throw new FinanceValidationError('originalAmount must be positive');
    if (!input.dueDate) throw new FinanceValidationError('dueDate is required');

    const jobOrder = await this.getJobOrderOrThrow(input.jobOrderReference);
    const sequence = (await this.repository.countRetentions()) + 1;
    const year = new Date().getFullYear();
    const retentionNumber = `RET-${year}-${String(sequence).padStart(6, '0')}`;

    return this.repository.insertRetention({ id: randomUUID(), retentionNumber, orgNodeId: jobOrder.orgNodeId, ...input });
  }

  async releaseRetention(id: string, amount: string): Promise<RetentionRecord> {
    const retentionRecord = await this.repository.findRetentionById(id);
    if (!retentionRecord) throw new FinanceNotFoundError(`retention ${id} does not exist`);
    if (retentionRecord.status !== 'active') {
      throw new FinanceValidationError(`retention ${id} is "${retentionRecord.status}" and cannot be released (must be "active")`);
    }

    const releaseAmount = Number(amount);
    if (!Number.isFinite(releaseAmount) || releaseAmount <= 0) throw new FinanceValidationError('release amount must be positive');

    const remaining = Number(retentionRecord.originalAmount) - Number(retentionRecord.releasedAmount);
    if (releaseAmount > remaining) {
      throw new FinanceValidationError(`release amount ${releaseAmount} exceeds remaining retention ${remaining}`);
    }

    const newReleasedTotal = (Number(retentionRecord.releasedAmount) + releaseAmount).toFixed(4);
    const isFullyReleased = Number(newReleasedTotal) >= Number(retentionRecord.originalAmount);
    return this.repository.releaseRetention(id, newReleasedTotal, isFullyReleased ? 'released' : 'active');
  }

  // --- Purchase Invoices & AP Accounting ---
  async getPurchaseInvoices(orgNodeId?: string, supplierId?: string): Promise<PurchaseInvoiceRecord[]> {
    return this.repository.listPurchaseInvoices(orgNodeId, supplierId);
  }

  async getPurchaseInvoice(id: string): Promise<PurchaseInvoiceRecord> {
    const found = await this.repository.findPurchaseInvoiceById(id);
    if (!found) throw new FinanceNotFoundError(`purchase invoice ${id} does not exist`);
    return found;
  }

  async createPurchaseInvoice(input: CreatePurchaseInvoiceInput): Promise<PurchaseInvoiceRecord> {
    if (!input.orgNodeId) throw new FinanceValidationError('orgNodeId is required');
    if (!input.supplierId) throw new FinanceValidationError('supplierId is required');
    if (!input.invoiceNumber || input.invoiceNumber.trim().length === 0) {
      throw new FinanceValidationError('supplier invoice number is required');
    }
    if (!input.lines || input.lines.length === 0) {
      throw new FinanceValidationError('purchase invoice must have at least one line');
    }

    let netTotal = 0;
    let taxTotal = 0;

    const computedLines = input.lines.map((l) => {
      const qty = Number(l.quantity);
      const cost = Number(l.unitCost);
      const rate = Number(l.taxRate ?? '14.00');

      if (!Number.isFinite(qty) || qty <= 0) throw new FinanceValidationError('line quantity must be positive');
      if (!Number.isFinite(cost) || cost < 0) throw new FinanceValidationError('line unitCost must be non-negative');

      const lineNet = qty * cost;
      const lineTax = (lineNet * rate) / 100;
      const lineGrand = lineNet + lineTax;

      netTotal += lineNet;
      taxTotal += lineTax;

      return {
        id: randomUUID(),
        itemId: l.itemId,
        quantity: l.quantity,
        unitCost: l.unitCost,
        taxRate: rate.toFixed(2),
        taxAmount: lineTax.toFixed(4),
        totalAmount: lineGrand.toFixed(4),
        purchaseReceiptId: l.purchaseReceiptId,
      };
    });

    const grandTotal = netTotal + taxTotal;
    const sequence = (await this.repository.countPurchaseInvoices()) + 1;
    const year = new Date().getFullYear();
    const systemNumber = `PINV-${year}-${String(sequence).padStart(6, '0')}`;

    return this.repository.insertPurchaseInvoice({
      ...input,
      id: randomUUID(),
      systemNumber,
      netAmount: netTotal.toFixed(4),
      taxAmount: taxTotal.toFixed(4),
      grandTotal: grandTotal.toFixed(4),
      computedLines,
    });
  }

  async postPurchaseInvoice(id: string): Promise<PurchaseInvoiceRecord> {
    const invoice = await this.getPurchaseInvoice(id);
    if (invoice.status !== 'draft') {
      throw new FinanceValidationError(`purchase invoice ${id} is "${invoice.status}" and cannot be posted (must be "draft")`);
    }

    if (this.accountingService && this.accountingRepo) {
      const config = await this.accountingRepo.findCompanyConfig(invoice.orgNodeId);
      const determinations = await this.accountingRepo.listAccountDeterminations(invoice.orgNodeId);

      const grniDet = determinations.find((d) => d.accountPurpose === 'purchase' || d.accountPurpose === 'grni');
      const grniAccountId = grniDet?.accountId ?? config?.defaultGrniAccountId;

      const taxDet = determinations.find((d) => d.accountPurpose === 'input_tax');
      const taxAccountId = taxDet?.accountId ?? config?.defaultInputTaxAccountId;

      const apDet = determinations.find((d) => d.accountPurpose === 'payable');
      const apAccountId = apDet?.accountId ?? config?.defaultPayableAccountId;

      if (grniAccountId && apAccountId) {
        const lines = [
          {
            accountId: grniAccountId,
            debitAmount: invoice.netAmount,
            creditAmount: '0',
            description: `[Auto] GRNI Clearance for PINV ${invoice.systemNumber} (Supplier Inv: ${invoice.invoiceNumber})`,
          },
        ];

        if (Number(invoice.taxAmount) > 0 && taxAccountId) {
          lines.push({
            accountId: taxAccountId,
            debitAmount: invoice.taxAmount,
            creditAmount: '0',
            description: `[Auto] Input VAT (14%) for PINV ${invoice.systemNumber}`,
          });
        }

        lines.push({
          accountId: apAccountId,
          debitAmount: '0',
          creditAmount: invoice.grandTotal,
          description: `[Auto] Payable to Supplier for PINV ${invoice.systemNumber}`,
          partyType: 'supplier',
          partyId: invoice.supplierId,
        } as any);

        const draftEntry = await this.accountingService.createEntry({
          orgNodeId: invoice.orgNodeId,
          description: `Purchase Invoice ${invoice.systemNumber} (${invoice.invoiceNumber})`,
          reference: invoice.systemNumber,
          entryDate: invoice.invoiceDate,
          isAutoGenerated: true,
          idempotencyKey: `purchase-invoice-${invoice.id}`,
          sourceEventType: 'purchase_invoice',
          lines,
        });

        await this.accountingService.postEntry(draftEntry.id);
      }
    }

    return this.repository.setPurchaseInvoiceStatus(id, 'posted');
  }

  async cancelPurchaseInvoice(id: string): Promise<PurchaseInvoiceRecord> {
    const invoice = await this.getPurchaseInvoice(id);
    if (invoice.status === 'posted') {
      throw new FinanceValidationError(`purchase invoice ${id} is already posted and cannot be cancelled`);
    }
    return this.repository.setPurchaseInvoiceStatus(id, 'cancelled');
  }

  // --- Sales Invoices & AR / Revenue Accounting ---
  async getSalesInvoices(orgNodeId?: string, customerId?: string): Promise<SalesInvoiceRecord[]> {
    return this.repository.listSalesInvoices(orgNodeId, customerId);
  }

  async getSalesInvoice(id: string): Promise<SalesInvoiceRecord> {
    const found = await this.repository.findSalesInvoiceById(id);
    if (!found) throw new FinanceNotFoundError(`sales invoice ${id} does not exist`);
    return found;
  }

  async createSalesInvoice(input: CreateSalesInvoiceInput): Promise<SalesInvoiceRecord> {
    if (!input.orgNodeId) throw new FinanceValidationError('orgNodeId is required');
    if (!input.customerId) throw new FinanceValidationError('customerId is required');
    if (!input.lines || input.lines.length === 0) {
      throw new FinanceValidationError('sales invoice must have at least one line');
    }

    let netTotal = 0;
    let taxTotal = 0;

    const computedLines = input.lines.map((l) => {
      const qty = Number(l.quantity);
      const price = Number(l.unitPrice);
      const rate = Number(l.taxRate ?? '14.00');

      if (!Number.isFinite(qty) || qty <= 0) throw new FinanceValidationError('line quantity must be positive');
      if (!Number.isFinite(price) || price < 0) throw new FinanceValidationError('line unitPrice must be non-negative');

      const lineNet = qty * price;
      const lineTax = (lineNet * rate) / 100;
      const lineGrand = lineNet + lineTax;

      netTotal += lineNet;
      taxTotal += lineTax;

      return {
        id: randomUUID(),
        itemId: l.itemId,
        quantity: l.quantity,
        unitPrice: l.unitPrice,
        taxRate: rate.toFixed(2),
        taxAmount: lineTax.toFixed(4),
        totalAmount: lineGrand.toFixed(4),
        deliveryOrderId: l.deliveryOrderId,
      };
    });

    const grandTotal = netTotal + taxTotal;
    const sequence = (await this.repository.countSalesInvoices()) + 1;
    const year = new Date().getFullYear();
    const invoiceNumber = `SINV-${year}-${String(sequence).padStart(6, '0')}`;

    return this.repository.insertSalesInvoice({
      ...input,
      id: randomUUID(),
      invoiceNumber,
      netAmount: netTotal.toFixed(4),
      taxAmount: taxTotal.toFixed(4),
      grandTotal: grandTotal.toFixed(4),
      computedLines,
    });
  }

  async postSalesInvoice(id: string): Promise<SalesInvoiceRecord> {
    const invoice = await this.getSalesInvoice(id);
    if (invoice.status !== 'draft') {
      throw new FinanceValidationError(`sales invoice ${id} is "${invoice.status}" and cannot be posted (must be "draft")`);
    }

    if (this.accountingService && this.accountingRepo) {
      const config = await this.accountingRepo.findCompanyConfig(invoice.orgNodeId);
      const determinations = await this.accountingRepo.listAccountDeterminations(invoice.orgNodeId);

      const arDet = determinations.find((d) => d.accountPurpose === 'receivable');
      const arAccountId = arDet?.accountId ?? config?.defaultReceivableAccountId;

      const revDet = determinations.find((d) => d.accountPurpose === 'revenue');
      const revAccountId = revDet?.accountId;

      const taxDet = determinations.find((d) => d.accountPurpose === 'output_tax');
      const taxAccountId = taxDet?.accountId ?? config?.defaultOutputTaxAccountId;

      if (arAccountId && revAccountId) {
        const lines = [
          {
            accountId: arAccountId,
            debitAmount: invoice.grandTotal,
            creditAmount: '0',
            description: `[Auto] Receivable for Sales Invoice ${invoice.invoiceNumber}`,
            partyType: 'customer',
            partyId: invoice.customerId,
          } as any,
          {
            accountId: revAccountId,
            debitAmount: '0',
            creditAmount: invoice.netAmount,
            description: `[Auto] Revenue for Sales Invoice ${invoice.invoiceNumber}`,
          },
        ];

        if (Number(invoice.taxAmount) > 0 && taxAccountId) {
          lines.push({
            accountId: taxAccountId,
            debitAmount: '0',
            creditAmount: invoice.taxAmount,
            description: `[Auto] Output VAT (14%) for Sales Invoice ${invoice.invoiceNumber}`,
          });
        }

        const draftEntry = await this.accountingService.createEntry({
          orgNodeId: invoice.orgNodeId,
          description: `Sales Invoice ${invoice.invoiceNumber}`,
          reference: invoice.invoiceNumber,
          entryDate: invoice.invoiceDate,
          isAutoGenerated: true,
          idempotencyKey: `sales-invoice-${invoice.id}`,
          sourceEventType: 'sales_invoice',
          lines,
        });

        await this.accountingService.postEntry(draftEntry.id);
      }
    }

    return this.repository.setSalesInvoiceStatus(id, 'posted');
  }

  async cancelSalesInvoice(id: string): Promise<SalesInvoiceRecord> {
    const invoice = await this.getSalesInvoice(id);
    if (invoice.status === 'posted') {
      throw new FinanceValidationError(`sales invoice ${id} is already posted and cannot be cancelled`);
    }
    return this.repository.setSalesInvoiceStatus(id, 'cancelled');
  }

  // --- Payments (Supplier Payments & Bank Outflow) ---
  async getPayments(orgNodeId?: string, supplierId?: string): Promise<PaymentRecord[]> {
    return this.repository.listPayments(orgNodeId, supplierId);
  }

  async getPayment(id: string): Promise<PaymentRecord> {
    const found = await this.repository.findPaymentById(id);
    if (!found) throw new FinanceNotFoundError(`payment ${id} does not exist`);
    return found;
  }

  async createPayment(input: CreatePaymentInput): Promise<PaymentRecord> {
    if (!input.orgNodeId) throw new FinanceValidationError('orgNodeId is required');
    if (!input.paidFromAccountId) throw new FinanceValidationError('paidFromAccountId (Bank/Cash account) is required');

    const amount = Number(input.amount);
    if (!Number.isFinite(amount) || amount <= 0) throw new FinanceValidationError('payment amount must be positive');

    const sequence = (await this.repository.countPayments()) + 1;
    const year = new Date().getFullYear();
    const paymentNumber = `PAY-${year}-${String(sequence).padStart(6, '0')}`;

    return this.repository.insertPayment({
      ...input,
      id: randomUUID(),
      paymentNumber,
      amount: amount.toFixed(4),
    });
  }

  async postPayment(id: string): Promise<PaymentRecord> {
    const p = await this.getPayment(id);
    if (p.status !== 'draft') {
      throw new FinanceValidationError(`payment ${id} is "${p.status}" and cannot be posted (must be "draft")`);
    }

    // Automated Double-Entry Posting for Supplier Payment:
    // [Dr: AP (Supplier Subledger) / Cr: Bank/Cash (paidFromAccountId)]
    if (this.accountingService && this.accountingRepo && p.paidFromAccountId) {
      const config = await this.accountingRepo.findCompanyConfig(p.orgNodeId);
      const determinations = await this.accountingRepo.listAccountDeterminations(p.orgNodeId);

      const apDet = determinations.find((d) => d.accountPurpose === 'payable');
      const apAccountId = apDet?.accountId ?? config?.defaultPayableAccountId;

      if (apAccountId) {
        const draftEntry = await this.accountingService.createEntry({
          orgNodeId: p.orgNodeId,
          description: `Supplier Payment ${p.paymentNumber}`,
          reference: p.paymentNumber,
          entryDate: p.paymentDate,
          isAutoGenerated: true,
          idempotencyKey: `payment-${p.id}`,
          sourceEventType: 'payment',
          lines: [
            {
              accountId: apAccountId,
              debitAmount: p.amount,
              creditAmount: '0',
              description: `[Auto] AP Settlement via Payment ${p.paymentNumber}`,
              partyType: 'supplier',
              partyId: p.supplierId ?? undefined,
            } as any,
            {
              accountId: p.paidFromAccountId,
              debitAmount: '0',
              creditAmount: p.amount,
              description: `[Auto] Bank/Cash Outflow for Payment ${p.paymentNumber}`,
            },
          ],
        });

        await this.accountingService.postEntry(draftEntry.id);
      }
    }

    return this.repository.setPaymentStatus(id, 'posted');
  }

  async cancelPayment(id: string): Promise<PaymentRecord> {
    const p = await this.getPayment(id);
    if (p.status === 'posted') {
      throw new FinanceValidationError(`payment ${id} is already posted and cannot be cancelled`);
    }
    return this.repository.setPaymentStatus(id, 'cancelled');
  }
}