import { FinanceService } from './finance.service';
import { FinanceRepository } from './finance.repository';
import { SalesService } from '../sales/sales.service';
import { AccountingService } from '../accounting/accounting.service';
import { AccountingRepository } from '../accounting/accounting.repository';
import { FinanceValidationError } from './finance.errors';
import type { PurchaseInvoiceRecord, CreatePurchaseInvoiceInput } from './finance.types';
import type {
  CompanyAccountingConfigRecord,
  AccountDeterminationRecord,
  JournalEntryRecord,
} from '../accounting/accounting.types';

describe('FinanceService — Purchase Invoices & AP Accounting Posting', () => {
  let financeService: FinanceService;
  let financeRepo: FinanceRepository;
  let salesService: SalesService;
  let accountingService: AccountingService;
  let accountingRepo: AccountingRepository;

  // Mock In-Memory State
  const mockInvoices: Map<string, PurchaseInvoiceRecord> = new Map();
  const mockPostedJournals: JournalEntryRecord[] = [];

  const mockOrgNodeId = 'org-company-1';
  const mockSupplierId = 'sup-steel-vendor-1';
  const mockGrniAccountId = 'acc-grni-clearing';
  const mockTaxAccountId = 'acc-input-vat-14';
  const mockApAccountId = 'acc-accounts-payable';

  beforeEach(() => {
    mockInvoices.clear();
    mockPostedJournals.length = 0;

    financeRepo = {
      countPurchaseInvoices: jest.fn().mockImplementation(async () => mockInvoices.size),
      findPurchaseInvoiceBySupplierNumber: jest.fn().mockResolvedValue(null),
      insertPurchaseInvoice: jest.fn().mockImplementation(async (input) => {
        const record: PurchaseInvoiceRecord = {
          id: input.id,
          invoiceNumber: input.invoiceNumber,
          systemNumber: input.systemNumber,
          orgNodeId: input.orgNodeId,
          supplierId: input.supplierId,
          invoiceDate: input.invoiceDate,
          dueDate: input.dueDate,
          currencyCode: input.currencyCode ?? 'EGP',
          exchangeRate: input.exchangeRate ?? '1.000000',
          netAmount: input.netAmount,
          taxAmount: input.taxAmount,
          grandTotal: input.grandTotal,
          status: 'draft',
          notes: input.notes ?? null,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          lines: input.computedLines.map((l: any) => ({
            ...l,
            purchaseInvoiceId: input.id,
            createdAt: new Date().toISOString(),
          })),
        };
        mockInvoices.set(input.id, record);
        return record;
      }),
      findPurchaseInvoiceById: jest.fn().mockImplementation(async (id: string) => {
        return mockInvoices.get(id) ?? null;
      }),
      setPurchaseInvoiceStatus: jest.fn().mockImplementation(async (id: string, status: any) => {
        const inv = mockInvoices.get(id);
        if (inv) {
          inv.status = status;
          inv.updatedAt = new Date().toISOString();
        }
        return inv;
      }),
      listPurchaseInvoices: jest
        .fn()
        .mockImplementation(async () => Array.from(mockInvoices.values())),
    } as unknown as FinanceRepository;

    salesService = {} as unknown as SalesService;

    accountingRepo = {
      findCompanyConfig: jest.fn().mockResolvedValue({
        orgNodeId: mockOrgNodeId,
        defaultGrniAccountId: mockGrniAccountId,
        defaultInputTaxAccountId: mockTaxAccountId,
        defaultPayableAccountId: mockApAccountId,
      } as CompanyAccountingConfigRecord),
      listAccountDeterminations: jest.fn().mockResolvedValue([
        {
          orgNodeId: mockOrgNodeId,
          accountPurpose: 'grni',
          accountId: mockGrniAccountId,
        } as AccountDeterminationRecord,
        {
          orgNodeId: mockOrgNodeId,
          accountPurpose: 'input_tax',
          accountId: mockTaxAccountId,
        } as AccountDeterminationRecord,
        {
          orgNodeId: mockOrgNodeId,
          accountPurpose: 'payable',
          accountId: mockApAccountId,
        } as AccountDeterminationRecord,
      ]),
    } as unknown as AccountingRepository;

    accountingService = {
      createEntry: jest.fn().mockImplementation(async (input) => {
        const je: JournalEntryRecord = {
          id: `je-${mockPostedJournals.length + 1}`,
          entryNumber: `JE-2026-00000${mockPostedJournals.length + 1}`,
          orgNodeId: input.orgNodeId,
          reference: input.reference ?? null,
          description: input.description,
          entryDate: input.entryDate ?? new Date().toISOString(),
          postedAt: null,
          status: 'draft',
          fiscalYearId: null,
          periodId: null,
          isAutoGenerated: true,
          idempotencyKey: input.idempotencyKey ?? null,
          sourceEventType: input.sourceEventType ?? null,
          lines: input.lines.map((l: any, idx: number) => ({
            id: `jl-${idx + 1}`,
            journalEntryId: `je-${mockPostedJournals.length + 1}`,
            accountId: l.accountId,
            debitAmount: l.debitAmount ?? '0',
            creditAmount: l.creditAmount ?? '0',
            description: l.description ?? null,
            partyType: l.partyType ?? null,
            partyId: l.partyId ?? null,
          })),
        };
        return je;
      }),
      postEntry: jest.fn().mockImplementation(async (id: string) => {
        const je: JournalEntryRecord = {
          id,
          entryNumber: 'JE-2026-000001',
          orgNodeId: mockOrgNodeId,
          reference: 'PINV-2026-000001',
          description: 'Posted',
          entryDate: new Date().toISOString(),
          postedAt: new Date().toISOString(),
          status: 'posted',
          lines: [],
        };
        mockPostedJournals.push(je);
        return je;
      }),
    } as unknown as AccountingService;

    financeService = new FinanceService(
      financeRepo,
      salesService,
      accountingService,
      accountingRepo,
    );
  });

  it('1. Create Purchase Invoice: should accurately calculate Net, 14% VAT, and Grand Total', async () => {
    const input: CreatePurchaseInvoiceInput = {
      orgNodeId: mockOrgNodeId,
      supplierId: mockSupplierId,
      invoiceNumber: 'SUP-INV-9988',
      invoiceDate: '2026-09-21T10:00:00.000Z',
      dueDate: '2026-10-21T10:00:00.000Z',
      lines: [
        {
          itemId: 'item-sheet-metal-1',
          quantity: '10',
          unitCost: '100.000000', // Net = 1000 EGP, VAT (14%) = 140 EGP, Line Total = 1140 EGP
          taxRate: '14.00',
        },
        {
          itemId: 'item-paint-powder-2',
          quantity: '5',
          unitCost: '200.000000', // Net = 1000 EGP, VAT (14%) = 140 EGP, Line Total = 1140 EGP
          taxRate: '14.00',
        },
      ],
    };

    const invoice = await financeService.createPurchaseInvoice(input);

    expect(invoice.systemNumber).toBe('PINV-2026-000001');
    expect(invoice.netAmount).toBe('2000.0000');
    expect(invoice.taxAmount).toBe('280.0000');
    expect(invoice.grandTotal).toBe('2280.0000');
    expect(invoice.status).toBe('draft');
    expect(invoice.lines.length).toBe(2);
    expect(invoice.lines[0]?.taxAmount).toBe('140.0000');
    expect(invoice.lines[0]?.totalAmount).toBe('1140.0000');
  });

  it('2. Validation: should reject invoice with missing lines or negative quantity', async () => {
    await expect(
      financeService.createPurchaseInvoice({
        orgNodeId: mockOrgNodeId,
        supplierId: mockSupplierId,
        invoiceNumber: 'INV-BAD-1',
        invoiceDate: '2026-09-21',
        dueDate: '2026-10-21',
        lines: [],
      }),
    ).rejects.toThrow(FinanceValidationError);

    await expect(
      financeService.createPurchaseInvoice({
        orgNodeId: mockOrgNodeId,
        supplierId: mockSupplierId,
        invoiceNumber: 'INV-BAD-2',
        invoiceDate: '2026-09-21',
        dueDate: '2026-10-21',
        lines: [
          {
            itemId: 'item-1',
            quantity: '-5',
            unitCost: '100',
          },
        ],
      }),
    ).rejects.toThrow(FinanceValidationError);
  });

  it('3. Post Purchase Invoice: should generate automated journal entry [Dr GRNI (Net) + Dr VAT (14%) / Cr AP (Supplier Total)]', async () => {
    // 1. Create Draft Invoice
    const invoice = await financeService.createPurchaseInvoice({
      orgNodeId: mockOrgNodeId,
      supplierId: mockSupplierId,
      invoiceNumber: 'SUP-INV-5544',
      invoiceDate: '2026-09-21',
      dueDate: '2026-10-21',
      lines: [
        {
          itemId: 'item-sheet-metal-1',
          quantity: '50',
          unitCost: '100.000000', // Net = 5000, VAT = 700, Grand = 5700
          taxRate: '14.00',
        },
      ],
    });

    // 2. Post the invoice
    const postedInvoice = await financeService.postPurchaseInvoice(invoice.id);

    expect(postedInvoice.status).toBe('posted');
    expect(accountingService.createEntry).toHaveBeenCalledWith(
      expect.objectContaining({
        orgNodeId: mockOrgNodeId,
        isAutoGenerated: true,
        idempotencyKey: `purchase-invoice-${invoice.id}`,
        lines: expect.arrayContaining([
          // Dr GRNI (5000)
          expect.objectContaining({
            accountId: mockGrniAccountId,
            debitAmount: '5000.0000',
            creditAmount: '0',
          }),
          // Dr Input VAT (700)
          expect.objectContaining({
            accountId: mockTaxAccountId,
            debitAmount: '700.0000',
            creditAmount: '0',
          }),
          // Cr AP (5700 with supplier partyId)
          expect.objectContaining({
            accountId: mockApAccountId,
            debitAmount: '0',
            creditAmount: '5700.0000',
            partyType: 'supplier',
            partyId: mockSupplierId,
          }),
        ]),
      }),
    );
    expect(accountingService.postEntry).toHaveBeenCalledTimes(1);
  });

  it('4. Security & State: should prevent re-posting or cancelling an already posted invoice', async () => {
    const invoice = await financeService.createPurchaseInvoice({
      orgNodeId: mockOrgNodeId,
      supplierId: mockSupplierId,
      invoiceNumber: 'SUP-INV-LOCK',
      invoiceDate: '2026-09-21',
      dueDate: '2026-10-21',
      lines: [{ itemId: 'item-1', quantity: '1', unitCost: '100' }],
    });

    await financeService.postPurchaseInvoice(invoice.id);

    // Try re-posting
    await expect(financeService.postPurchaseInvoice(invoice.id)).rejects.toThrow(
      FinanceValidationError,
    );

    // Try cancelling
    await expect(financeService.cancelPurchaseInvoice(invoice.id)).rejects.toThrow(
      FinanceValidationError,
    );
  });
});
