import { FinanceService } from './finance.service';
import { FinanceRepository } from './finance.repository';
import { SalesService } from '../sales/sales.service';
import { AccountingService } from '../accounting/accounting.service';
import { AccountingRepository } from '../accounting/accounting.repository';
import { FinanceValidationError } from './finance.errors';
import type {
  SalesInvoiceRecord,
  CreateSalesInvoiceInput,
} from './finance.types';
import type {
  CompanyAccountingConfigRecord,
  AccountDeterminationRecord,
  JournalEntryRecord,
} from '../accounting/accounting.types';

describe('FinanceService — Sales Invoices & AR / Revenue Accounting Posting', () => {
  let financeService: FinanceService;
  let financeRepo: FinanceRepository;
  let salesService: SalesService;
  let accountingService: AccountingService;
  let accountingRepo: AccountingRepository;

  // Mock In-Memory State
  const mockInvoices: Map<string, SalesInvoiceRecord> = new Map();
  const mockPostedJournals: JournalEntryRecord[] = [];

  const mockOrgNodeId = 'org-company-1';
  const mockCustomerId = 'cust-medical-hospital-1';
  const mockArAccountId = 'acc-accounts-receivable';
  const mockRevenueAccountId = 'acc-sales-revenue';
  const mockTaxAccountId = 'acc-output-vat-14';

  beforeEach(() => {
    mockInvoices.clear();
    mockPostedJournals.length = 0;

    financeRepo = {
      countSalesInvoices: jest.fn().mockImplementation(async () => mockInvoices.size),
      insertSalesInvoice: jest.fn().mockImplementation(async (input) => {
        const record: SalesInvoiceRecord = {
          id: input.id,
          invoiceNumber: input.invoiceNumber,
          orgNodeId: input.orgNodeId,
          customerId: input.customerId,
          jobOrderReference: input.jobOrderReference ?? null,
          invoiceDate: input.invoiceDate,
          dueDate: input.dueDate,
          currencyCode: input.currencyCode ?? 'EGP',
          exchangeRate: input.exchangeRate ?? '1.000000',
          netAmount: input.netAmount,
          taxAmount: input.taxAmount,
          grandTotal: input.grandTotal,
          status: 'draft',
          notes: input.notes ?? null,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          lines: input.computedLines.map((l: any) => ({
            ...l,
            salesInvoiceId: input.id,
            createdAt: new Date().toISOString(),
          })),
        };
        mockInvoices.set(input.id, record);
        return record;
      }),
      findSalesInvoiceById: jest.fn().mockImplementation(async (id: string) => {
        return mockInvoices.get(id) ?? null;
      }),
      setSalesInvoiceStatus: jest.fn().mockImplementation(async (id: string, status: any) => {
        const inv = mockInvoices.get(id);
        if (inv) {
          inv.status = status;
          inv.updatedAt = new Date().toISOString();
        }
        return inv;
      }),
      listSalesInvoices: jest.fn().mockImplementation(async () => Array.from(mockInvoices.values())),
    } as unknown as FinanceRepository;

    salesService = {} as unknown as SalesService;

    accountingRepo = {
      findCompanyConfig: jest.fn().mockResolvedValue({
        orgNodeId: mockOrgNodeId,
        defaultReceivableAccountId: mockArAccountId,
        defaultOutputTaxAccountId: mockTaxAccountId,
      } as CompanyAccountingConfigRecord),
      listAccountDeterminations: jest.fn().mockResolvedValue([
        {
          orgNodeId: mockOrgNodeId,
          accountPurpose: 'receivable',
          accountId: mockArAccountId,
        } as AccountDeterminationRecord,
        {
          orgNodeId: mockOrgNodeId,
          accountPurpose: 'revenue',
          accountId: mockRevenueAccountId,
        } as AccountDeterminationRecord,
        {
          orgNodeId: mockOrgNodeId,
          accountPurpose: 'output_tax',
          accountId: mockTaxAccountId,
        } as AccountDeterminationRecord,
      ]),
    } as unknown as AccountingRepository;

    accountingService = {
      createEntry: jest.fn().mockImplementation(async (input) => {
        const je: JournalEntryRecord = {
          id: `je-${mockPostedJournals.length + 1}`,
          entryNumber: `JE-2026-00000${mockPostedJournals.length + 1}`,
          orgNodeId: input.orgNodeId,
          reference: input.reference ?? null,
          description: input.description,
          entryDate: input.entryDate ?? new Date().toISOString(),
          postedAt: null,
          status: 'draft',
          fiscalYearId: null,
          periodId: null,
          isAutoGenerated: true,
          idempotencyKey: input.idempotencyKey ?? null,
          sourceEventType: input.sourceEventType ?? null,
          lines: input.lines.map((l: any, idx: number) => ({
            id: `jl-${idx + 1}`,
            journalEntryId: `je-${mockPostedJournals.length + 1}`,
            accountId: l.accountId,
            debitAmount: l.debitAmount ?? '0',
            creditAmount: l.creditAmount ?? '0',
            description: l.description ?? null,
            partyType: l.partyType ?? null,
            partyId: l.partyId ?? null,
          })),
        };
        return je;
      }),
      postEntry: jest.fn().mockImplementation(async (id: string) => {
        const je: JournalEntryRecord = {
          id,
          entryNumber: 'JE-2026-000001',
          orgNodeId: mockOrgNodeId,
          reference: 'SINV-2026-000001',
          description: 'Posted',
          entryDate: new Date().toISOString(),
          postedAt: new Date().toISOString(),
          status: 'posted',
          lines: [],
        };
        mockPostedJournals.push(je);
        return je;
      }),
    } as unknown as AccountingService;

    financeService = new FinanceService(
      financeRepo,
      salesService,
      accountingService,
      accountingRepo,
    );
  });

  it('1. Create Sales Invoice: should accurately calculate Net, 14% VAT, and Grand Total', async () => {
    const input: CreateSalesInvoiceInput = {
      orgNodeId: mockOrgNodeId,
      customerId: mockCustomerId,
      jobOrderReference: 'JO-2026-000001',
      invoiceDate: '2026-09-21T10:00:00.000Z',
      dueDate: '2026-10-21T10:00:00.000Z',
      lines: [
        {
          itemId: 'item-cabinet-drawer-60',
          quantity: '2',
          unitPrice: '5000.0000', // Net = 10000 EGP, VAT (14%) = 1400 EGP, Line Total = 11400 EGP
          taxRate: '14.00',
        },
      ],
    };

    const invoice = await financeService.createSalesInvoice(input);

    expect(invoice.invoiceNumber).toBe('SINV-2026-000001');
    expect(invoice.netAmount).toBe('10000.0000');
    expect(invoice.taxAmount).toBe('1400.0000');
    expect(invoice.grandTotal).toBe('11400.0000');
    expect(invoice.status).toBe('draft');
    expect(invoice.lines.length).toBe(1);
    expect(invoice.lines[0]?.taxAmount).toBe('1400.0000');
    expect(invoice.lines[0]?.totalAmount).toBe('11400.0000');
  });

  it('2. Validation: should reject invoice with missing lines or negative price/quantity', async () => {
    await expect(
      financeService.createSalesInvoice({
        orgNodeId: mockOrgNodeId,
        customerId: mockCustomerId,
        invoiceDate: '2026-09-21',
        dueDate: '2026-10-21',
        lines: [],
      }),
    ).rejects.toThrow(FinanceValidationError);

    await expect(
      financeService.createSalesInvoice({
        orgNodeId: mockOrgNodeId,
        customerId: mockCustomerId,
        invoiceDate: '2026-09-21',
        dueDate: '2026-10-21',
        lines: [
          {
            itemId: 'item-1',
            quantity: '5',
            unitPrice: '-100',
          },
        ],
      }),
    ).rejects.toThrow(FinanceValidationError);
  });

  it('3. Post Sales Invoice: should generate automated journal entry [Dr AR (Customer Total) / Cr Revenue (Net) + Cr VAT (14%)]', async () => {
    // 1. Create Draft Sales Invoice
    const invoice = await financeService.createSalesInvoice({
      orgNodeId: mockOrgNodeId,
      customerId: mockCustomerId,
      jobOrderReference: 'JO-2026-000001',
      invoiceDate: '2026-09-21',
      dueDate: '2026-10-21',
      lines: [
        {
          itemId: 'item-cabinet-drawer-60',
          quantity: '1',
          unitPrice: '10000.0000', // Net = 10000, VAT = 1400, Grand = 11400
          taxRate: '14.00',
        },
      ],
    });

    // 2. Post the invoice
    const postedInvoice = await financeService.postSalesInvoice(invoice.id);

    expect(postedInvoice.status).toBe('posted');
    expect(accountingService.createEntry).toHaveBeenCalledWith(
      expect.objectContaining({
        orgNodeId: mockOrgNodeId,
        isAutoGenerated: true,
        idempotencyKey: `sales-invoice-${invoice.id}`,
        lines: expect.arrayContaining([
          // Dr AR (11400 with customer partyId)
          expect.objectContaining({
            accountId: mockArAccountId,
            debitAmount: '11400.0000',
            creditAmount: '0',
            partyType: 'customer',
            partyId: mockCustomerId,
          }),
          // Cr Revenue (10000)
          expect.objectContaining({
            accountId: mockRevenueAccountId,
            debitAmount: '0',
            creditAmount: '10000.0000',
          }),
          // Cr Output VAT (1400)
          expect.objectContaining({
            accountId: mockTaxAccountId,
            debitAmount: '0',
            creditAmount: '1400.0000',
          }),
        ]),
      }),
    );
    expect(accountingService.postEntry).toHaveBeenCalledTimes(1);
  });

  it('4. Security & State: should prevent re-posting or cancelling an already posted sales invoice', async () => {
    const invoice = await financeService.createSalesInvoice({
      orgNodeId: mockOrgNodeId,
      customerId: mockCustomerId,
      invoiceDate: '2026-09-21',
      dueDate: '2026-10-21',
      lines: [{ itemId: 'item-1', quantity: '1', unitPrice: '500' }],
    });

    await financeService.postSalesInvoice(invoice.id);

    // Try re-posting
    await expect(financeService.postSalesInvoice(invoice.id)).rejects.toThrow(
      FinanceValidationError,
    );

    // Try cancelling
    await expect(financeService.cancelSalesInvoice(invoice.id)).rejects.toThrow(
      FinanceValidationError,
    );
  });
});