ALTER TABLE "accounting"."company_accounting_config" ADD COLUMN "default_bank_account_id" uuid;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD COLUMN "default_cash_account_id" uuid;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD COLUMN "default_income_account_id" uuid;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD COLUMN "default_inventory_account_id" uuid;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD COLUMN "default_round_off_account_id" uuid;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD COLUMN "default_write_off_account_id" uuid;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD COLUMN "default_exchange_gain_loss_account_id" uuid;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD COLUMN "default_depreciation_expense_account_id" uuid;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD COLUMN "enforce_default_accounts" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD CONSTRAINT "company_accounting_config_default_bank_account_id_chart_of_accounts_id_fk" FOREIGN KEY ("default_bank_account_id") REFERENCES "accounting"."chart_of_accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD CONSTRAINT "company_accounting_config_default_cash_account_id_chart_of_accounts_id_fk" FOREIGN KEY ("default_cash_account_id") REFERENCES "accounting"."chart_of_accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD CONSTRAINT "company_accounting_config_default_income_account_id_chart_of_accounts_id_fk" FOREIGN KEY ("default_income_account_id") REFERENCES "accounting"."chart_of_accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD CONSTRAINT "company_accounting_config_default_inventory_account_id_chart_of_accounts_id_fk" FOREIGN KEY ("default_inventory_account_id") REFERENCES "accounting"."chart_of_accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD CONSTRAINT "company_accounting_config_default_round_off_account_id_chart_of_accounts_id_fk" FOREIGN KEY ("default_round_off_account_id") REFERENCES "accounting"."chart_of_accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD CONSTRAINT "company_accounting_config_default_write_off_account_id_chart_of_accounts_id_fk" FOREIGN KEY ("default_write_off_account_id") REFERENCES "accounting"."chart_of_accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD CONSTRAINT "company_accounting_config_default_exchange_gain_loss_account_id_chart_of_accounts_id_fk" FOREIGN KEY ("default_exchange_gain_loss_account_id") REFERENCES "accounting"."chart_of_accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounting"."company_accounting_config" ADD CONSTRAINT "company_accounting_config_default_depreciation_expense_account_id_chart_of_accounts_id_fk" FOREIGN KEY ("default_depreciation_expense_account_id") REFERENCES "accounting"."chart_of_accounts"("id") ON DELETE set null ON UPDATE no action;