import { Injectable } from '@nestjs/common';
import { and, eq, sql } from 'drizzle-orm';
import { DatabaseService } from '../../core/database/database.service';
import { AccountingNotFoundError, AccountingValidationError } from './accounting.errors';
import { AccountingRepository } from './accounting.repository';
import {
  accountingDimension,
  accountingDimensionValue,
  accountType,
  chartOfAccounts,
  costCenter,
  journalEntry,
  journalLine,
  journalLineDimension,
} from './accounting.schema';
import type {
  CreateJournalEntryInput,
  CreateJournalLineInput,
  JournalEntryRecord,
} from './accounting.types';

const PNL_TYPES = ['revenue', 'cogs', 'expense'];

/** Balance side check (pure): would the account end up on the wrong side? */
export function wrongSide(mustBe: 'debit' | 'credit' | null, balanceAfter: number): boolean {
  if (!mustBe) return false;
  return mustBe === 'debit' ? balanceAfter < -0.0001 : balanceAfter > 0.0001;
}

/**
 * Plan item 41 — account controls on every journal entry:
 * cost center required on revenue / expense lines (company default filled in), the account's natural
 * balance side, frozen accounts, and user-defined accounting dimensions (mandatory ones enforced).
 * No posting to a parent account already existed (AccountingService.createEntry).
 */
@Injectable()
export class AccountControlsService {
  constructor(
    private readonly database: DatabaseService,
    private readonly repository: AccountingRepository,
  ) {}

  /** Validates and normalises the lines before anything is written; returns them with cost centers filled in. */
  async prepare(input: CreateJournalEntryInput): Promise<CreateJournalLineInput[]> {
    const config = await this.repository.findCompanyConfig(input.orgNodeId);
    const dims = await this.database.db
      .select()
      .from(accountingDimension)
      .where(
        and(
          eq(accountingDimension.orgNodeId, input.orgNodeId),
          eq(accountingDimension.isActive, true),
        ),
      );
    const out: CreateJournalLineInput[] = [];
    for (const line of input.lines) {
      const acc = await this.account(line.accountId);
      if (acc.isFrozen)
        throw new AccountingValidationError(`الحساب ${acc.code} مجمّد — مينفعش أي قيد عليه`);
      const isPnl = PNL_TYPES.includes(acc.typeCode);
      let costCenterId = line.costCenterId;
      if (!costCenterId && isPnl) {
        costCenterId = config?.defaultCostCenterId ?? undefined;
        if (!costCenterId && !input.isAutoGenerated) {
          throw new AccountingValidationError(
            `الحساب ${acc.code} حساب إيرادات/مصروفات — لازم مركز تكلفة (أو حدد مركز تكلفة افتراضي للشركة)`,
          );
        }
      }
      if (costCenterId) await this.checkCostCenter(costCenterId, input.orgNodeId);
      await this.checkDimensions(line, dims, isPnl, input.isAutoGenerated ?? false, acc.code);
      out.push({ ...line, costCenterId });
    }
    await this.checkBalanceSides(input.orgNodeId, out);
    return out;
  }

  /** Re-checks at posting: accounts may have been frozen, or balances moved, since the draft was written. */
  async checkAtPosting(entry: JournalEntryRecord): Promise<void> {
    if (!entry.orgNodeId) return;
    for (const l of entry.lines) {
      const acc = await this.account(l.accountId);
      if (acc.isFrozen)
        throw new AccountingValidationError(`الحساب ${acc.code} مجمّد — مينفعش ترحيل قيد عليه`);
    }
    await this.checkBalanceSides(entry.orgNodeId, entry.lines);
  }

  async saveDimensions(entry: JournalEntryRecord, lines: CreateJournalLineInput[]): Promise<void> {
    const rows = entry.lines.flatMap((l, i) =>
      (lines[i]?.dimensions ?? []).map((d) => ({
        journalLineId: l.id,
        dimensionId: d.dimensionId,
        valueId: d.valueId,
      })),
    );
    if (rows.length > 0) await this.database.db.insert(journalLineDimension).values(rows);
  }

  // --- dimensions & account settings API ---
  async createDimension(input: {
    orgNodeId: string;
    code: string;
    name: string;
    mandatoryForPnl?: boolean;
    mandatoryForBalanceSheet?: boolean;
  }): Promise<typeof accountingDimension.$inferSelect> {
    if (!input.code?.trim() || !input.name?.trim())
      throw new AccountingValidationError('code and name are required');
    const rows = await this.database.db
      .insert(accountingDimension)
      .values({
        orgNodeId: input.orgNodeId,
        code: input.code.trim(),
        name: input.name.trim(),
        mandatoryForPnl: input.mandatoryForPnl ?? false,
        mandatoryForBalanceSheet: input.mandatoryForBalanceSheet ?? false,
      })
      .returning();
    return rows[0]!;
  }

  async addDimensionValue(
    dimensionId: string,
    input: { code: string; name: string },
  ): Promise<typeof accountingDimensionValue.$inferSelect> {
    const dim = (
      await this.database.db
        .select()
        .from(accountingDimension)
        .where(eq(accountingDimension.id, dimensionId))
        .limit(1)
    )[0];
    if (!dim) throw new AccountingNotFoundError(`dimension ${dimensionId} does not exist`);
    const rows = await this.database.db
      .insert(accountingDimensionValue)
      .values({ dimensionId, code: input.code.trim(), name: input.name.trim() })
      .returning();
    return rows[0]!;
  }

  async listDimensions(orgNodeId: string): Promise<
    Array<
      typeof accountingDimension.$inferSelect & {
        values: Array<typeof accountingDimensionValue.$inferSelect>;
      }
    >
  > {
    const dims = await this.database.db
      .select()
      .from(accountingDimension)
      .where(eq(accountingDimension.orgNodeId, orgNodeId));
    return Promise.all(
      dims.map(async (d) => ({
        ...d,
        values: await this.database.db
          .select()
          .from(accountingDimensionValue)
          .where(eq(accountingDimensionValue.dimensionId, d.id)),
      })),
    );
  }

  /** Posted totals per dimension value and account. */
  async dimensionReport(
    dimensionId: string,
    from?: string,
    to?: string,
  ): Promise<
    Array<{
      valueCode: string;
      valueName: string;
      accountCode: string;
      debit: string;
      credit: string;
      net: string;
    }>
  > {
    const conds = [
      eq(journalLineDimension.dimensionId, dimensionId),
      eq(journalEntry.status, 'posted'),
    ];
    if (from) conds.push(sql`${journalEntry.entryDate} >= ${new Date(from)}`);
    if (to) conds.push(sql`${journalEntry.entryDate} <= ${new Date(to)}`);
    const rows = await this.database.db
      .select({
        valueCode: accountingDimensionValue.code,
        valueName: accountingDimensionValue.name,
        accountCode: chartOfAccounts.code,
        debit: sql<string>`sum(${journalLine.debitAmount})`,
        credit: sql<string>`sum(${journalLine.creditAmount})`,
      })
      .from(journalLineDimension)
      .innerJoin(journalLine, eq(journalLine.id, journalLineDimension.journalLineId))
      .innerJoin(journalEntry, eq(journalEntry.id, journalLine.journalEntryId))
      .innerJoin(
        accountingDimensionValue,
        eq(accountingDimensionValue.id, journalLineDimension.valueId),
      )
      .innerJoin(chartOfAccounts, eq(chartOfAccounts.id, journalLine.accountId))
      .where(and(...conds))
      .groupBy(accountingDimensionValue.code, accountingDimensionValue.name, chartOfAccounts.code);
    return rows.map((r) => ({
      ...r,
      debit: Number(r.debit).toFixed(4),
      credit: Number(r.credit).toFixed(4),
      net: (Number(r.debit) - Number(r.credit)).toFixed(4),
    }));
  }

  async setAccountControls(
    accountId: string,
    input: { balanceMustBe?: 'debit' | 'credit' | null; isFrozen?: boolean },
  ): Promise<{ accountId: string; balanceMustBe: string | null; isFrozen: boolean }> {
    const acc = await this.account(accountId);
    if (input.balanceMustBe) {
      const bal = await this.postedBalance(accountId);
      if (wrongSide(input.balanceMustBe, bal))
        throw new AccountingValidationError(
          `رصيد الحساب ${acc.code} دلوقتي ${bal.toFixed(2)} — عكس الاتجاه المطلوب`,
        );
    }
    const set: { balanceMustBe?: string | null; isFrozen?: boolean; updatedAt: Date } = {
      updatedAt: new Date(),
    };
    if (input.balanceMustBe !== undefined) set.balanceMustBe = input.balanceMustBe;
    if (input.isFrozen !== undefined) set.isFrozen = input.isFrozen;
    const rows = await this.database.db
      .update(chartOfAccounts)
      .set(set)
      .where(eq(chartOfAccounts.id, accountId))
      .returning({
        balanceMustBe: chartOfAccounts.balanceMustBe,
        isFrozen: chartOfAccounts.isFrozen,
      });
    return { accountId, balanceMustBe: rows[0]!.balanceMustBe, isFrozen: rows[0]!.isFrozen };
  }

  private async checkBalanceSides(
    orgNodeId: string,
    lines: Array<{ accountId: string; debitAmount?: string; creditAmount?: string }>,
  ): Promise<void> {
    const net = new Map<string, number>();
    for (const l of lines)
      net.set(
        l.accountId,
        (net.get(l.accountId) ?? 0) + Number(l.debitAmount ?? 0) - Number(l.creditAmount ?? 0),
      );
    for (const [accountId, delta] of net) {
      const acc = await this.account(accountId);
      if (!acc.balanceMustBe) continue;
      const after = (await this.postedBalance(accountId, orgNodeId)) + delta;
      if (wrongSide(acc.balanceMustBe as 'debit' | 'credit', after)) {
        throw new AccountingValidationError(
          `الحساب ${acc.code} رصيده لازم يفضل ${acc.balanceMustBe === 'debit' ? 'مدين' : 'دائن'} — بعد القيد هيبقى ${after.toFixed(2)}`,
        );
      }
    }
  }

  private async checkCostCenter(id: string, orgNodeId: string): Promise<void> {
    const cc = (
      await this.database.db.select().from(costCenter).where(eq(costCenter.id, id)).limit(1)
    )[0];
    if (!cc) throw new AccountingNotFoundError(`cost center ${id} does not exist`);
    if (cc.orgNodeId !== orgNodeId)
      throw new AccountingValidationError(`مركز التكلفة ${cc.code} تبع شركة تانية`);
    if (cc.isGroup)
      throw new AccountingValidationError(`مركز التكلفة ${cc.code} مجموعة — اختار مركز فرعي`);
    if (!cc.isActive) throw new AccountingValidationError(`مركز التكلفة ${cc.code} موقوف`);
  }

  private async checkDimensions(
    line: CreateJournalLineInput,
    dims: Array<typeof accountingDimension.$inferSelect>,
    isPnl: boolean,
    isAuto: boolean,
    accountCode: string,
  ): Promise<void> {
    const given = line.dimensions ?? [];
    if (new Set(given.map((d) => d.dimensionId)).size !== given.length)
      throw new AccountingValidationError('the same dimension is given twice on one line');
    for (const d of given) {
      if (!dims.some((x) => x.id === d.dimensionId))
        throw new AccountingValidationError(
          `dimension ${d.dimensionId} is not an active dimension of this company`,
        );
      const v = (
        await this.database.db
          .select()
          .from(accountingDimensionValue)
          .where(eq(accountingDimensionValue.id, d.valueId))
          .limit(1)
      )[0];
      if (!v || v.dimensionId !== d.dimensionId || !v.isActive)
        throw new AccountingValidationError(
          `value ${d.valueId} does not belong to dimension ${d.dimensionId}`,
        );
    }
    if (isAuto) return; // system postings are not blocked by user-defined dimensions
    for (const dim of dims) {
      const mandatory = isPnl ? dim.mandatoryForPnl : dim.mandatoryForBalanceSheet;
      if (mandatory && !given.some((g) => g.dimensionId === dim.id))
        throw new AccountingValidationError(
          `البُعد "${dim.name}" إجباري على الحساب ${accountCode}`,
        );
    }
  }

  private async account(
    id: string,
  ): Promise<{ code: string; typeCode: string; isFrozen: boolean; balanceMustBe: string | null }> {
    const r = (
      await this.database.db
        .select({
          code: chartOfAccounts.code,
          typeCode: accountType.code,
          isFrozen: chartOfAccounts.isFrozen,
          balanceMustBe: chartOfAccounts.balanceMustBe,
        })
        .from(chartOfAccounts)
        .innerJoin(accountType, eq(accountType.id, chartOfAccounts.accountTypeId))
        .where(eq(chartOfAccounts.id, id))
        .limit(1)
    )[0];
    if (!r) throw new AccountingNotFoundError(`account ${id} does not exist`);
    return r;
  }

  private async postedBalance(accountId: string, orgNodeId?: string): Promise<number> {
    const conds = [eq(journalLine.accountId, accountId), eq(journalEntry.status, 'posted')];
    if (orgNodeId) conds.push(eq(journalEntry.orgNodeId, orgNodeId));
    const r = await this.database.db
      .select({
        v: sql<string>`coalesce(sum(${journalLine.debitAmount} - ${journalLine.creditAmount}), 0)`,
      })
      .from(journalLine)
      .innerJoin(journalEntry, eq(journalEntry.id, journalLine.journalEntryId))
      .where(and(...conds));
    return Number(r[0]?.v ?? 0);
  }
}
