import { Injectable } from '@nestjs/common';
import { and, asc, eq, gte, lte } from 'drizzle-orm';
import { DatabaseService } from '../../core/database/database.service';
import {
  accountDetermination, accountingPeriod, accountType, chartOfAccounts,
  companyAccountingConfig, costCenter, fiscalYear, journalEntry, journalLine,
} from './accounting.schema';
import type {
  AccountDeterminationRecord, AccountingPeriodRecord, AccountingPeriodStatus,
  AccountTypeRecord, ChartAccountStatus, ChartOfAccountsRecord,
  CompanyAccountingConfigRecord, CostCenterRecord, CreateAccountDeterminationInput,
  CreateAccountingPeriodInput, CreateAccountTypeInput, CreateChartOfAccountsInput,
  CreateCostCenterInput, CreateFiscalYearInput, CreateJournalEntryInput,
  FiscalYearRecord, JournalEntryRecord, JournalEntryStatus, JournalLineRecord,
  NormalBalance, UpsertCompanyAccountingConfigInput,
} from './accounting.types';

const atColumns = { id: accountType.id, code: accountType.code, name: accountType.name, normalBalance: accountType.normalBalance };
const coaColumns = {
  id: chartOfAccounts.id, code: chartOfAccounts.code, name: chartOfAccounts.name, orgNodeId: chartOfAccounts.orgNodeId,
  accountTypeId: chartOfAccounts.accountTypeId, parentId: chartOfAccounts.parentId,
  isLeaf: chartOfAccounts.isLeaf, status: chartOfAccounts.status,
};
const fyColumns = {
  id: fiscalYear.id, orgNodeId: fiscalYear.orgNodeId, name: fiscalYear.name,
  startDate: fiscalYear.startDate, endDate: fiscalYear.endDate, isClosed: fiscalYear.isClosed,
};
const periodColumns = {
  id: accountingPeriod.id, fiscalYearId: accountingPeriod.fiscalYearId, periodNumber: accountingPeriod.periodNumber,
  name: accountingPeriod.name, startDate: accountingPeriod.startDate, endDate: accountingPeriod.endDate, status: accountingPeriod.status,
};
const ccColumns = {
  id: costCenter.id, orgNodeId: costCenter.orgNodeId, code: costCenter.code, name: costCenter.name,
  parentId: costCenter.parentId, isGroup: costCenter.isGroup, isActive: costCenter.isActive,
};
const configColumns = {
  id: companyAccountingConfig.id, orgNodeId: companyAccountingConfig.orgNodeId,
  baseCurrency: companyAccountingConfig.baseCurrency, inventoryValuationMethod: companyAccountingConfig.inventoryValuationMethod,
  defaultGrniAccountId: companyAccountingConfig.defaultGrniAccountId, defaultWipAccountId: companyAccountingConfig.defaultWipAccountId,
  defaultCogsAccountId: companyAccountingConfig.defaultCogsAccountId, defaultMfgVarianceAccountId: companyAccountingConfig.defaultMfgVarianceAccountId,
  defaultPayableAccountId: companyAccountingConfig.defaultPayableAccountId, defaultReceivableAccountId: companyAccountingConfig.defaultReceivableAccountId,
  defaultInputTaxAccountId: companyAccountingConfig.defaultInputTaxAccountId, defaultOutputTaxAccountId: companyAccountingConfig.defaultOutputTaxAccountId,
  defaultScrapAccountId: companyAccountingConfig.defaultScrapAccountId, defaultStockAdjustmentAccountId: companyAccountingConfig.defaultStockAdjustmentAccountId,
  defaultOhAppliedAccountId: companyAccountingConfig.defaultOhAppliedAccountId,
};
const detColumns = {
  id: accountDetermination.id, orgNodeId: accountDetermination.orgNodeId, determinationType: accountDetermination.determinationType,
  referenceId: accountDetermination.referenceId, accountPurpose: accountDetermination.accountPurpose, accountId: accountDetermination.accountId,
};
const jeColumns = {
  id: journalEntry.id, entryNumber: journalEntry.entryNumber, orgNodeId: journalEntry.orgNodeId, reference: journalEntry.reference,
  description: journalEntry.description, entryDate: journalEntry.entryDate, postedAt: journalEntry.postedAt, status: journalEntry.status,
  fiscalYearId: journalEntry.fiscalYearId, periodId: journalEntry.periodId, isAutoGenerated: journalEntry.isAutoGenerated,
  idempotencyKey: journalEntry.idempotencyKey, sourceEventType: journalEntry.sourceEventType,
};
const jlColumns = {
  id: journalLine.id, journalEntryId: journalLine.journalEntryId, accountId: journalLine.accountId,
  debitAmount: journalLine.debitAmount, creditAmount: journalLine.creditAmount, description: journalLine.description,
  partyType: journalLine.partyType, partyId: journalLine.partyId, costCenterId: journalLine.costCenterId, jobOrderId: journalLine.jobOrderId,
};

@Injectable()
export class AccountingRepository {
  constructor(private readonly database: DatabaseService) {}

  // --- Account Types ---
  async listAccountTypes(): Promise<AccountTypeRecord[]> {
    const rows = await this.database.db.select(atColumns).from(accountType).orderBy(asc(accountType.code));
    return rows.map((r) => ({ id: r.id, code: r.code, name: r.name, normalBalance: r.normalBalance as NormalBalance }));
  }
  async findAccountTypeByCode(code: string): Promise<AccountTypeRecord | null> {
    const rows = await this.database.db.select(atColumns).from(accountType).where(eq(accountType.code, code)).limit(1);
    return rows[0] ? { id: rows[0].id, code: rows[0].code, name: rows[0].name, normalBalance: rows[0].normalBalance as NormalBalance } : null;
  }
  async findAccountTypeById(id: string): Promise<AccountTypeRecord | null> {
    const rows = await this.database.db.select(atColumns).from(accountType).where(eq(accountType.id, id)).limit(1);
    return rows[0] ? { id: rows[0].id, code: rows[0].code, name: rows[0].name, normalBalance: rows[0].normalBalance as NormalBalance } : null;
  }
  async insertAccountType(input: CreateAccountTypeInput & { id: string }): Promise<AccountTypeRecord> {
    const rows = await this.database.db.insert(accountType).values(input).returning(atColumns);
    return { id: rows[0]!.id, code: rows[0]!.code, name: rows[0]!.name, normalBalance: rows[0]!.normalBalance as NormalBalance };
  }

  // --- Chart of Accounts ---
  async listAccounts(): Promise<ChartOfAccountsRecord[]> {
    const rows = await this.database.db.select(coaColumns).from(chartOfAccounts).orderBy(asc(chartOfAccounts.code));
    return rows.map((r) => ({
      id: r.id, code: r.code, name: r.name, orgNodeId: r.orgNodeId, accountTypeId: r.accountTypeId,
      parentId: r.parentId, isLeaf: r.isLeaf === 'yes', status: r.status as ChartAccountStatus,
    }));
  }
  async findAccountById(id: string): Promise<ChartOfAccountsRecord | null> {
    const rows = await this.database.db.select(coaColumns).from(chartOfAccounts).where(eq(chartOfAccounts.id, id)).limit(1);
    return rows[0] ? {
      id: rows[0].id, code: rows[0].code, name: rows[0].name, orgNodeId: rows[0].orgNodeId,
      accountTypeId: rows[0].accountTypeId, parentId: rows[0].parentId,
      isLeaf: rows[0].isLeaf === 'yes', status: rows[0].status as ChartAccountStatus,
    } : null;
  }
  async findAccountByCode(orgNodeId: string, code: string): Promise<ChartOfAccountsRecord | null> {
    const rows = await this.database.db.select(coaColumns).from(chartOfAccounts)
      .where(and(eq(chartOfAccounts.orgNodeId, orgNodeId), eq(chartOfAccounts.code, code))).limit(1);
    return rows[0] ? {
      id: rows[0].id, code: rows[0].code, name: rows[0].name, orgNodeId: rows[0].orgNodeId,
      accountTypeId: rows[0].accountTypeId, parentId: rows[0].parentId,
      isLeaf: rows[0].isLeaf === 'yes', status: rows[0].status as ChartAccountStatus,
    } : null;
  }
  async insertAccount(input: CreateChartOfAccountsInput & { id: string }): Promise<ChartOfAccountsRecord> {
    const rows = await this.database.db.insert(chartOfAccounts).values({
      id: input.id, code: input.code, name: input.name, orgNodeId: input.orgNodeId,
      accountTypeId: input.accountTypeId, parentId: input.parentId ?? null,
    }).returning(coaColumns);
    const r = rows[0]!;
    return {
      id: r.id, code: r.code, name: r.name, orgNodeId: r.orgNodeId, accountTypeId: r.accountTypeId,
      parentId: r.parentId, isLeaf: r.isLeaf === 'yes', status: r.status as ChartAccountStatus,
    };
  }
  async markAsParent(id: string): Promise<void> {
    await this.database.db.update(chartOfAccounts).set({ isLeaf: 'no' }).where(eq(chartOfAccounts.id, id));
  }

  // --- Fiscal Year ---
  async listFiscalYears(orgNodeId?: string): Promise<FiscalYearRecord[]> {
    const query = this.database.db.select(fyColumns).from(fiscalYear);
    const rows = orgNodeId ? await query.where(eq(fiscalYear.orgNodeId, orgNodeId)).orderBy(asc(fiscalYear.startDate)) : await query.orderBy(asc(fiscalYear.startDate));
    return rows.map((r) => ({ id: r.id, orgNodeId: r.orgNodeId, name: r.name, startDate: r.startDate.toISOString(), endDate: r.endDate.toISOString(), isClosed: r.isClosed }));
  }
  async findFiscalYearById(id: string): Promise<FiscalYearRecord | null> {
    const rows = await this.database.db.select(fyColumns).from(fiscalYear).where(eq(fiscalYear.id, id)).limit(1);
    return rows[0] ? { id: rows[0].id, orgNodeId: rows[0].orgNodeId, name: rows[0].name, startDate: rows[0].startDate.toISOString(), endDate: rows[0].endDate.toISOString(), isClosed: rows[0].isClosed } : null;
  }
  async findFiscalYearByDate(orgNodeId: string, date: Date): Promise<FiscalYearRecord | null> {
    const rows = await this.database.db.select(fyColumns).from(fiscalYear)
      .where(and(eq(fiscalYear.orgNodeId, orgNodeId), lte(fiscalYear.startDate, date), gte(fiscalYear.endDate, date))).limit(1);
    return rows[0] ? { id: rows[0].id, orgNodeId: rows[0].orgNodeId, name: rows[0].name, startDate: rows[0].startDate.toISOString(), endDate: rows[0].endDate.toISOString(), isClosed: rows[0].isClosed } : null;
  }
  async insertFiscalYear(input: CreateFiscalYearInput & { id: string }): Promise<FiscalYearRecord> {
    const rows = await this.database.db.insert(fiscalYear).values({
      id: input.id, orgNodeId: input.orgNodeId, name: input.name,
      startDate: new Date(input.startDate), endDate: new Date(input.endDate),
    }).returning(fyColumns);
    const r = rows[0]!;
    return { id: r.id, orgNodeId: r.orgNodeId, name: r.name, startDate: r.startDate.toISOString(), endDate: r.endDate.toISOString(), isClosed: r.isClosed };
  }
  async closeFiscalYear(id: string): Promise<void> {
    await this.database.db.update(fiscalYear).set({ isClosed: true }).where(eq(fiscalYear.id, id));
  }

  // --- Accounting Period ---
  async listPeriods(fiscalYearId: string): Promise<AccountingPeriodRecord[]> {
    const rows = await this.database.db.select(periodColumns).from(accountingPeriod).where(eq(accountingPeriod.fiscalYearId, fiscalYearId)).orderBy(asc(accountingPeriod.periodNumber));
    return rows.map((r) => ({
      id: r.id, fiscalYearId: r.fiscalYearId, periodNumber: r.periodNumber, name: r.name,
      startDate: r.startDate.toISOString(), endDate: r.endDate.toISOString(), status: r.status as AccountingPeriodStatus,
    }));
  }
  async findPeriodById(id: string): Promise<AccountingPeriodRecord | null> {
    const rows = await this.database.db.select(periodColumns).from(accountingPeriod).where(eq(accountingPeriod.id, id)).limit(1);
    return rows[0] ? {
      id: rows[0].id, fiscalYearId: rows[0].fiscalYearId, periodNumber: rows[0].periodNumber, name: rows[0].name,
      startDate: rows[0].startDate.toISOString(), endDate: rows[0].endDate.toISOString(), status: rows[0].status as AccountingPeriodStatus,
    } : null;
  }
  async findPeriodByDate(fiscalYearId: string, date: Date): Promise<AccountingPeriodRecord | null> {
    const rows = await this.database.db.select(periodColumns).from(accountingPeriod)
      .where(and(eq(accountingPeriod.fiscalYearId, fiscalYearId), lte(accountingPeriod.startDate, date), gte(accountingPeriod.endDate, date))).limit(1);
    return rows[0] ? {
      id: rows[0].id, fiscalYearId: rows[0].fiscalYearId, periodNumber: rows[0].periodNumber, name: rows[0].name,
      startDate: rows[0].startDate.toISOString(), endDate: rows[0].endDate.toISOString(), status: rows[0].status as AccountingPeriodStatus,
    } : null;
  }
  async insertPeriod(input: CreateAccountingPeriodInput & { id: string }): Promise<AccountingPeriodRecord> {
    const rows = await this.database.db.insert(accountingPeriod).values({
      id: input.id, fiscalYearId: input.fiscalYearId, periodNumber: input.periodNumber, name: input.name,
      startDate: new Date(input.startDate), endDate: new Date(input.endDate),
    }).returning(periodColumns);
    const r = rows[0]!;
    return {
      id: r.id, fiscalYearId: r.fiscalYearId, periodNumber: r.periodNumber, name: r.name,
      startDate: r.startDate.toISOString(), endDate: r.endDate.toISOString(), status: r.status as AccountingPeriodStatus,
    };
  }
  async setPeriodStatus(id: string, status: AccountingPeriodStatus): Promise<AccountingPeriodRecord> {
    const rows = await this.database.db.update(accountingPeriod).set({ status }).where(eq(accountingPeriod.id, id)).returning(periodColumns);
    const r = rows[0]!;
    return {
      id: r.id, fiscalYearId: r.fiscalYearId, periodNumber: r.periodNumber, name: r.name,
      startDate: r.startDate.toISOString(), endDate: r.endDate.toISOString(), status: r.status as AccountingPeriodStatus,
    };
  }

  // --- Cost Center ---
  async listCostCenters(orgNodeId?: string): Promise<CostCenterRecord[]> {
    const query = this.database.db.select(ccColumns).from(costCenter);
    const rows = orgNodeId ? await query.where(eq(costCenter.orgNodeId, orgNodeId)).orderBy(asc(costCenter.code)) : await query.orderBy(asc(costCenter.code));
    return rows.map((r) => ({ id: r.id, orgNodeId: r.orgNodeId, code: r.code, name: r.name, parentId: r.parentId, isGroup: r.isGroup, isActive: r.isActive }));
  }
  async findCostCenterById(id: string): Promise<CostCenterRecord | null> {
    const rows = await this.database.db.select(ccColumns).from(costCenter).where(eq(costCenter.id, id)).limit(1);
    return rows[0] ? { id: rows[0].id, orgNodeId: rows[0].orgNodeId, code: rows[0].code, name: rows[0].name, parentId: rows[0].parentId, isGroup: rows[0].isGroup, isActive: rows[0].isActive } : null;
  }
  async findCostCenterByCode(orgNodeId: string, code: string): Promise<CostCenterRecord | null> {
    const rows = await this.database.db.select(ccColumns).from(costCenter).where(and(eq(costCenter.orgNodeId, orgNodeId), eq(costCenter.code, code))).limit(1);
    return rows[0] ? { id: rows[0].id, orgNodeId: rows[0].orgNodeId, code: rows[0].code, name: rows[0].name, parentId: rows[0].parentId, isGroup: rows[0].isGroup, isActive: rows[0].isActive } : null;
  }
  async insertCostCenter(input: CreateCostCenterInput & { id: string }): Promise<CostCenterRecord> {
    const rows = await this.database.db.insert(costCenter).values({
      id: input.id, orgNodeId: input.orgNodeId, code: input.code, name: input.name,
      parentId: input.parentId ?? null, isGroup: input.isGroup ?? false,
    }).returning(ccColumns);
    const r = rows[0]!;
    return { id: r.id, orgNodeId: r.orgNodeId, code: r.code, name: r.name, parentId: r.parentId, isGroup: r.isGroup, isActive: r.isActive };
  }

  // --- Company Accounting Config ---
  async findCompanyConfig(orgNodeId: string): Promise<CompanyAccountingConfigRecord | null> {
    const rows = await this.database.db.select(configColumns).from(companyAccountingConfig).where(eq(companyAccountingConfig.orgNodeId, orgNodeId)).limit(1);
    return rows[0] ?? null;
  }
  async upsertCompanyConfig(input: UpsertCompanyAccountingConfigInput & { id: string }): Promise<CompanyAccountingConfigRecord> {
    const existing = await this.findCompanyConfig(input.orgNodeId);
    if (existing) {
      const rows = await this.database.db.update(companyAccountingConfig).set({ ...input, updatedAt: new Date() }).where(eq(companyAccountingConfig.orgNodeId, input.orgNodeId)).returning(configColumns);
      return rows[0]!;
    }
    const rows = await this.database.db.insert(companyAccountingConfig).values(input).returning(configColumns);
    return rows[0]!;
  }

  // --- Account Determination ---
  async listAccountDeterminations(orgNodeId: string): Promise<AccountDeterminationRecord[]> {
    const rows = await this.database.db.select(detColumns).from(accountDetermination).where(eq(accountDetermination.orgNodeId, orgNodeId));
    return rows;
  }
  async insertAccountDetermination(input: CreateAccountDeterminationInput & { id: string }): Promise<AccountDeterminationRecord> {
    const rows = await this.database.db.insert(accountDetermination).values(input).returning(detColumns);
    return rows[0]!;
  }

  // --- Journal Entries ---
  async listEntries(): Promise<JournalEntryRecord[]> {
    const entries = await this.database.db.select(jeColumns).from(journalEntry).orderBy(asc(journalEntry.entryNumber));
    const allLines = await this.database.db.select(jlColumns).from(journalLine);
    return entries.map((e) => ({
      id: e.id, entryNumber: e.entryNumber, orgNodeId: e.orgNodeId, reference: e.reference, description: e.description,
      entryDate: e.entryDate.toISOString(), postedAt: e.postedAt ? e.postedAt.toISOString() : null, status: e.status as JournalEntryStatus,
      fiscalYearId: e.fiscalYearId, periodId: e.periodId, isAutoGenerated: e.isAutoGenerated,
      idempotencyKey: e.idempotencyKey, sourceEventType: e.sourceEventType,
      lines: allLines.filter((l) => l.journalEntryId === e.id).map((l) => ({
        id: l.id, journalEntryId: l.journalEntryId, accountId: l.accountId, debitAmount: l.debitAmount,
        creditAmount: l.creditAmount, description: l.description, partyType: l.partyType, partyId: l.partyId,
        costCenterId: l.costCenterId, jobOrderId: l.jobOrderId,
      })),
    }));
  }
  async findEntryById(id: string): Promise<JournalEntryRecord | null> {
    const rows = await this.database.db.select(jeColumns).from(journalEntry).where(eq(journalEntry.id, id)).limit(1);
    if (!rows[0]) return null;
    const lines = await this.database.db.select(jlColumns).from(journalLine).where(eq(journalLine.journalEntryId, id));
    const e = rows[0];
    return {
      id: e.id, entryNumber: e.entryNumber, orgNodeId: e.orgNodeId, reference: e.reference, description: e.description,
      entryDate: e.entryDate.toISOString(), postedAt: e.postedAt ? e.postedAt.toISOString() : null, status: e.status as JournalEntryStatus,
      fiscalYearId: e.fiscalYearId, periodId: e.periodId, isAutoGenerated: e.isAutoGenerated,
      idempotencyKey: e.idempotencyKey, sourceEventType: e.sourceEventType,
      lines: lines.map((l) => ({
        id: l.id, journalEntryId: l.journalEntryId, accountId: l.accountId, debitAmount: l.debitAmount,
        creditAmount: l.creditAmount, description: l.description, partyType: l.partyType, partyId: l.partyId,
        costCenterId: l.costCenterId, jobOrderId: l.jobOrderId,
      })),
    };
  }
  async countEntries(): Promise<number> {
    const rows = await this.database.db.select({ id: journalEntry.id }).from(journalEntry);
    return rows.length;
  }
  async insertEntry(input: CreateJournalEntryInput & { id: string; entryNumber: string }): Promise<JournalEntryRecord> {
    const rows = await this.database.db.insert(journalEntry).values({
      id: input.id, entryNumber: input.entryNumber, orgNodeId: input.orgNodeId, reference: input.reference ?? null,
      description: input.description, entryDate: input.entryDate ? new Date(input.entryDate) : new Date(),
      fiscalYearId: input.fiscalYearId ?? null, periodId: input.periodId ?? null,
      isAutoGenerated: input.isAutoGenerated ?? false, idempotencyKey: input.idempotencyKey ?? null,
      sourceEventType: input.sourceEventType ?? null,
    }).returning(jeColumns);
    const inserted = rows[0]!;
    const lines: JournalLineRecord[] = [];
    for (const line of input.lines) {
      const lineRows = await this.database.db.insert(journalLine).values({
        journalEntryId: inserted.id, accountId: line.accountId,
        debitAmount: line.debitAmount ?? '0', creditAmount: line.creditAmount ?? '0', description: line.description,
        partyType: line.partyType ?? null, partyId: line.partyId ?? null,
        costCenterId: line.costCenterId ?? null, jobOrderId: line.jobOrderId ?? null,
      }).returning(jlColumns);
      const l = lineRows[0]!;
      lines.push({
        id: l.id, journalEntryId: l.journalEntryId, accountId: l.accountId, debitAmount: l.debitAmount,
        creditAmount: l.creditAmount, description: l.description, partyType: l.partyType, partyId: l.partyId,
        costCenterId: l.costCenterId, jobOrderId: l.jobOrderId,
      });
    }
    return {
      id: inserted.id, entryNumber: inserted.entryNumber, orgNodeId: inserted.orgNodeId, reference: inserted.reference,
      description: inserted.description, entryDate: inserted.entryDate.toISOString(), postedAt: null,
      status: inserted.status as JournalEntryStatus, fiscalYearId: inserted.fiscalYearId, periodId: inserted.periodId,
      isAutoGenerated: inserted.isAutoGenerated, idempotencyKey: inserted.idempotencyKey, sourceEventType: inserted.sourceEventType,
      lines,
    };
  }
  async setEntryStatus(id: string, status: JournalEntryStatus): Promise<JournalEntryRecord> {
    const fields: { status: JournalEntryStatus; postedAt?: Date } = { status };
    if (status === 'posted') fields.postedAt = new Date();
    const rows = await this.database.db.update(journalEntry).set(fields).where(eq(journalEntry.id, id)).returning(jeColumns);
    const lines = await this.database.db.select(jlColumns).from(journalLine).where(eq(journalLine.journalEntryId, id));
    const e = rows[0]!;
    return {
      id: e.id, entryNumber: e.entryNumber, orgNodeId: e.orgNodeId, reference: e.reference, description: e.description,
      entryDate: e.entryDate.toISOString(), postedAt: e.postedAt ? e.postedAt.toISOString() : null, status: e.status as JournalEntryStatus,
      fiscalYearId: e.fiscalYearId, periodId: e.periodId, isAutoGenerated: e.isAutoGenerated,
      idempotencyKey: e.idempotencyKey, sourceEventType: e.sourceEventType,
      lines: lines.map((l) => ({
        id: l.id, journalEntryId: l.journalEntryId, accountId: l.accountId, debitAmount: l.debitAmount,
        creditAmount: l.creditAmount, description: l.description, partyType: l.partyType, partyId: l.partyId,
        costCenterId: l.costCenterId, jobOrderId: l.jobOrderId,
      })),
    };
  }

  async listAllPostedLinesWithAccounts(): Promise<Array<{ accountId: string; code: string; name: string; debit: string; credit: string }>> {
    const rows = await this.database.db.select({
      accountId: chartOfAccounts.id, code: chartOfAccounts.code, name: chartOfAccounts.name,
      debit: journalLine.debitAmount, credit: journalLine.creditAmount, entryStatus: journalEntry.status,
    }).from(journalLine)
      .innerJoin(chartOfAccounts, eq(journalLine.accountId, chartOfAccounts.id))
      .innerJoin(journalEntry, eq(journalLine.journalEntryId, journalEntry.id));
    return rows.filter((r) => r.entryStatus === 'posted').map(({ accountId, code, name, debit, credit }) => ({ accountId, code, name, debit, credit }));
  }
}