import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsIn,
  IsNumber,
  IsNumberString,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  ValidateNested,
} from 'class-validator';
import type { AccountingPeriodStatus } from './accounting.types';

export class CreateAccountTypeDto {
  @IsString() @MaxLength(64) code!: string;
  @IsString() @MaxLength(255) name!: string;
  @IsIn(['debit', 'credit']) normalBalance!: 'debit' | 'credit';
}

export class CreateChartOfAccountsDto {
  @IsString() @MaxLength(64) code!: string;
  @IsString() @MaxLength(255) name!: string;
  @IsUUID() orgNodeId!: string;
  @IsUUID() accountTypeId!: string;
  @IsOptional() @IsUUID() parentId?: string;
}

// --- Fiscal Year DTOs ---
export class CreateFiscalYearDto {
  @IsUUID() orgNodeId!: string;
  @IsString() @MaxLength(100) name!: string;
  @IsString() startDate!: string;
  @IsString() endDate!: string;
}

// --- Accounting Period DTOs ---
export class SetPeriodStatusDto {
  @IsIn(['open', 'closed', 'locked']) status!: AccountingPeriodStatus;
}

// --- Cost Center DTOs ---
export class CreateCostCenterDto {
  @IsUUID() orgNodeId!: string;
  @IsString() @MaxLength(64) code!: string;
  @IsString() @MaxLength(255) name!: string;
  @IsOptional() @IsUUID() parentId?: string;
  @IsOptional() @IsBoolean() isGroup?: boolean;
}

// --- Company Accounting Config DTOs ---
export class UpsertCompanyAccountingConfigDto {
  @IsOptional() @IsString() baseCurrency?: string;
  @IsOptional() @IsIn(['weighted_average', 'fifo', 'standard']) inventoryValuationMethod?: string;
  @IsOptional() @IsUUID() defaultGrniAccountId?: string;
  @IsOptional() @IsUUID() defaultWipAccountId?: string;
  @IsOptional() @IsUUID() defaultCogsAccountId?: string;
  @IsOptional() @IsUUID() defaultMfgVarianceAccountId?: string;
  @IsOptional() @IsUUID() defaultPayableAccountId?: string;
  @IsOptional() @IsUUID() defaultReceivableAccountId?: string;
  @IsOptional() @IsUUID() defaultInputTaxAccountId?: string;
  @IsOptional() @IsUUID() defaultOutputTaxAccountId?: string;
  @IsOptional() @IsUUID() defaultScrapAccountId?: string;
  @IsOptional() @IsUUID() defaultStockAdjustmentAccountId?: string;
  @IsOptional() @IsUUID() defaultOhAppliedAccountId?: string;
}

// --- Account Determination DTOs ---
export class CreateAccountDeterminationDto {
  @IsUUID() orgNodeId!: string;
  @IsIn(['item_category', 'warehouse', 'default']) determinationType!: 'item_category' | 'warehouse' | 'default';
  @IsOptional() @IsUUID() referenceId?: string;
  @IsString() accountPurpose!: string;
  @IsUUID() accountId!: string;
}

// --- Journal Entries DTOs ---
export class JournalLineDto {
  @IsUUID() accountId!: string;
  @IsOptional() @IsNumberString() debitAmount?: string;
  @IsOptional() @IsNumberString() creditAmount?: string;
  @IsOptional() @IsString() description?: string;
  @IsOptional() @IsIn(['customer', 'supplier']) partyType?: 'customer' | 'supplier';
  @IsOptional() @IsUUID() partyId?: string;
  @IsOptional() @IsUUID() costCenterId?: string;
  @IsOptional() @IsUUID() jobOrderId?: string;
}

export class CreateJournalEntryDto {
  @IsUUID() orgNodeId!: string;
  @IsString() @MaxLength(500) description!: string;
  @IsOptional() @IsString() reference?: string;
  @IsOptional() @IsString() entryDate?: string;
  @IsOptional() @IsUUID() fiscalYearId?: string;
  @IsOptional() @IsUUID() periodId?: string;
  @IsOptional() @IsBoolean() isAutoGenerated?: boolean;
  @IsOptional() @IsString() idempotencyKey?: string;
  @IsOptional() @IsString() sourceEventType?: string;
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => JournalLineDto)
  lines!: JournalLineDto[];
}