import { AccountingService } from './accounting.service';
import { AccountingRepository } from './accounting.repository';
import { AccountingValidationError } from './accounting.errors';
import type {
  CompanyAccountingConfigRecord,
  AccountDeterminationRecord,
  JournalEntryRecord,
} from './accounting.types';

describe('AccountingService — VAT Return & Tax Settlement Engine', () => {
  let accountingService: AccountingService;
  let accountingRepo: AccountingRepository;

  const mockOrgNodeId = 'org-medical-factory-1';
  const mockInputTaxAccountId = 'acc-input-vat-14';
  const mockOutputTaxAccountId = 'acc-output-vat-14';
  const mockTaxAuthorityPayableAccountId = 'acc-tax-authority-payable';

  let mockPostedJournals: JournalEntryRecord[] = [];
  let journalCounter = 0;

  beforeEach(() => {
    mockPostedJournals = [];
    journalCounter = 0;

    accountingRepo = {
      findCompanyConfig: jest.fn().mockResolvedValue({
        orgNodeId: mockOrgNodeId,
        defaultInputTaxAccountId: mockInputTaxAccountId,
        defaultOutputTaxAccountId: mockOutputTaxAccountId,
      } as CompanyAccountingConfigRecord),

      listAccountDeterminations: jest.fn().mockResolvedValue([
        {
          orgNodeId: mockOrgNodeId,
          accountPurpose: 'input_tax',
          accountId: mockInputTaxAccountId,
        } as AccountDeterminationRecord,
        {
          orgNodeId: mockOrgNodeId,
          accountPurpose: 'output_tax',
          accountId: mockOutputTaxAccountId,
        } as AccountDeterminationRecord,
      ]),

      listAllPostedLinesWithDetails: jest.fn().mockImplementation(async () => [
        // Purchase Invoices: Input Tax Debits (Paid to suppliers) = 5,600 EGP
        {
          accountId: mockInputTaxAccountId,
          code: '1401',
          name: 'ضريبة القيمة المضافة - مدخلات',
          typeCode: 'asset',
          normalBalance: 'debit',
          debit: '5600.0000',
          credit: '0.0000',
          entryDate: new Date('2026-09-10'),
          partyType: null,
          partyId: null,
          journalEntryId: 'je-pinv-1',
          entryNumber: 'JE-PINV-001',
          description: 'ضريبة مدخلات مشتريات صاج وبودرة',
        },
        // Sales Invoices: Output Tax Credits (Collected from customers) = 14,000 EGP
        {
          accountId: mockOutputTaxAccountId,
          code: '2401',
          name: 'ضريبة القيمة المضافة - مخرجات',
          typeCode: 'liability',
          normalBalance: 'credit',
          debit: '0.0000',
          credit: '14000.0000',
          entryDate: new Date('2026-09-15'),
          partyType: null,
          partyId: null,
          journalEntryId: 'je-sinv-1',
          entryNumber: 'JE-SINV-001',
          description: 'ضريبة مخرجات مبيعات وحدات أدراج',
        },
      ]),

      findFiscalYearByDate: jest.fn().mockResolvedValue(null),
      findAccountById: jest.fn().mockResolvedValue({ id: 'acc-1', isLeaf: true, orgNodeId: mockOrgNodeId }),
      countEntries: jest.fn().mockImplementation(async () => journalCounter),
      findEntryById: jest.fn().mockImplementation(async (id: string) => mockPostedJournals.find((j) => j.id === id) ?? null),
      insertEntry: jest.fn().mockImplementation(async (input) => {
        journalCounter++;
        const entry: JournalEntryRecord = {
          id: `je-vat-${journalCounter}`,
          entryNumber: `JE-VAT-2026-000${journalCounter}`,
          orgNodeId: input.orgNodeId,
          reference: input.reference ?? null,
          description: input.description,
          entryDate: input.entryDate ?? new Date().toISOString(),
          postedAt: null,
          status: 'draft',
          fiscalYearId: null,
          periodId: null,
          isAutoGenerated: true,
          idempotencyKey: input.idempotencyKey ?? null,
          sourceEventType: input.sourceEventType ?? null,
          lines: input.lines.map((l: any, idx: number) => ({
            id: `jl-${idx + 1}`,
            journalEntryId: `je-vat-${journalCounter}`,
            accountId: l.accountId,
            debitAmount: l.debitAmount ?? '0',
            creditAmount: l.creditAmount ?? '0',
            description: l.description,
          })),
        };
        mockPostedJournals.push(entry);
        return entry;
      }),
      setEntryStatus: jest.fn().mockImplementation(async (id: string, status: any) => {
        const found = mockPostedJournals.find((j) => j.id === id);
        if (found) {
          found.status = status;
          found.postedAt = new Date().toISOString();
        }
        return found!;
      }),
    } as unknown as AccountingRepository;

    accountingService = new AccountingService(accountingRepo);
  });

  it('1. VAT Report Calculation: should accurately compute Output Tax, Input Tax, and Net Payable', async () => {
    const report = await accountingService.getVatReport(mockOrgNodeId);

    // Output VAT = 14,000 | Input VAT = 5,600 -> Net Payable = 8,400 EGP
    expect(report.totalOutputTax).toBe('14000.0000');
    expect(report.totalInputTax).toBe('5600.0000');
    expect(report.netTaxPayable).toBe('8400.0000');
    expect(report.status).toBe('payable');
  });

  it('2. Post VAT Settlement: should generate balanced double-entry [Dr Output VAT / Cr Input VAT + Cr Tax Authority]', async () => {
    const result = await accountingService.postVatSettlement(
      mockOrgNodeId,
      '2026-09-30',
      mockTaxAuthorityPayableAccountId,
    );

    expect(result.journalEntry.status).toBe('posted');
    expect(result.vatSummary.netTaxPayable).toBe('8400.0000');

    expect(accountingRepo.insertEntry).toHaveBeenCalledWith(
      expect.objectContaining({
        orgNodeId: mockOrgNodeId,
        isAutoGenerated: true,
        sourceEventType: 'vat_settlement',
        lines: expect.arrayContaining([
          // 1. Dr: Output VAT (14,000) to clear credit balance
          expect.objectContaining({
            accountId: mockOutputTaxAccountId,
            debitAmount: '14000.0000',
            creditAmount: '0',
          }),
          // 2. Cr: Input VAT (5,600) to clear debit balance
          expect.objectContaining({
            accountId: mockInputTaxAccountId,
            debitAmount: '0',
            creditAmount: '5600.0000',
          }),
          // 3. Cr: Tax Authority Payable (8,400) for net amount due
          expect.objectContaining({
            accountId: mockTaxAuthorityPayableAccountId,
            debitAmount: '0',
            creditAmount: '8400.0000',
          }),
        ]),
      }),
    );
  });

  it('3. Refundable VAT Case: should record net tax receivable when input tax exceeds output tax', async () => {
    // When purchases exceed sales (e.g. buying expensive machines): Input = 20,000, Output = 5,000
    (accountingRepo.listAllPostedLinesWithDetails as jest.Mock).mockResolvedValueOnce([
      {
        accountId: mockInputTaxAccountId,
        debit: '20000.0000',
        credit: '0.0000',
        entryDate: new Date('2026-09-10'),
      },
      {
        accountId: mockOutputTaxAccountId,
        debit: '0.0000',
        credit: '5000.0000',
        entryDate: new Date('2026-09-15'),
      },
    ]);

    const report = await accountingService.getVatReport(mockOrgNodeId);

    expect(report.totalInputTax).toBe('20000.0000');
    expect(report.totalOutputTax).toBe('5000.0000');
    expect(report.netTaxPayable).toBe('15000.0000');
    expect(report.status).toBe('refundable'); // Credit balance to be refunded/carried forward
  });

  it('4. Validation: should throw error if VAT accounts are not configured', async () => {
    (accountingRepo.findCompanyConfig as jest.Mock).mockResolvedValueOnce({});
    (accountingRepo.listAccountDeterminations as jest.Mock).mockResolvedValueOnce([]);

    await expect(
      accountingService.postVatSettlement(
        mockOrgNodeId,
        '2026-09-30',
        mockTaxAuthorityPayableAccountId,
      ),
    ).rejects.toThrow(AccountingValidationError);
  });
});