import type { AccountingRepository } from './accounting.repository';
import type { AccountingService } from './accounting.service';
import type { CreateJournalEntryInput, JournalEntryRecord } from './accounting.types';
import { JournalReversalService } from './journal-reversal.service';

describe('Frozen journal entries — reversal only (plan item 31)', () => {
  let entries: Map<string, JournalEntryRecord & { reversalOf?: string }>;
  let service: JournalReversalService;
  let created: CreateJournalEntryInput[];

  const entry = (id: string, extra: Partial<JournalEntryRecord> = {}): JournalEntryRecord => ({
    id,
    entryNumber: `JE-${id}`,
    orgNodeId: 'co',
    reference: 'REF',
    description: 'd',
    entryDate: '',
    postedAt: '',
    status: 'posted',
    isAutoGenerated: false,
    sourceEventType: null,
    lines: [
      {
        id: 'l1',
        journalEntryId: id,
        accountId: 'cash',
        debitAmount: '100.0000',
        creditAmount: '0',
        description: 'x',
        partyType: 'customer',
        partyId: 'c1',
      },
      {
        id: 'l2',
        journalEntryId: id,
        accountId: 'sales',
        debitAmount: '0',
        creditAmount: '100.0000',
        description: 'y',
      },
    ],
    ...extra,
  });

  beforeEach(() => {
    created = [];
    entries = new Map([
      ['m1', entry('m1')],
      [
        'auto',
        entry('auto', {
          isAutoGenerated: true,
          sourceEventType: 'sales_invoice',
          reference: 'SI-1',
        }),
      ],
      ['draft', entry('draft', { status: 'draft' })],
    ]);
    const repo = {
      findEntryById: jest.fn(async (id: string) => entries.get(id) ?? null),
      findReversalLinks: jest.fn(async (id: string) => ({
        reversedById: [...entries.values()].find((e) => e.reversalOf === id)?.id ?? null,
        reversalOfId: entries.get(id)?.reversalOf ?? null,
        reason: null,
      })),
      markReversal: jest.fn(async (rid: string, oid: string) => {
        entries.get(rid)!.reversalOf = oid;
      }),
      listPostedEntryIdsBySource: jest.fn(async (t: string, ref: string) =>
        [...entries.values()]
          .filter((e) => e.sourceEventType === t && e.reference === ref && e.status === 'posted')
          .map((e) => e.id),
      ),
    } as unknown as AccountingRepository;
    const accounting = {
      createEntry: jest.fn(async (i: CreateJournalEntryInput) => {
        created.push(i);
        const id = `r${created.length}`;
        entries.set(id, {
          ...entry(id, { status: 'draft', sourceEventType: i.sourceEventType }),
          lines: [],
        });
        return entries.get(id)!;
      }),
      postEntry: jest.fn(async (id: string) => {
        entries.get(id)!.status = 'posted';
        return entries.get(id)!;
      }),
    } as unknown as AccountingService;
    service = new JournalReversalService(accounting, repo);
  });

  it('1. a manual posted entry is reversed by a mirror entry (debit ↔ credit), with a reason', async () => {
    await expect(service.reverseManual('m1', { reason: ' ' })).rejects.toThrow(/reason/);
    const { reversal } = await service.reverseManual('m1', { reason: 'قيد غلط' });
    expect(reversal.status).toBe('posted');
    expect(created[0]!.lines.map((l) => [l.accountId, l.debitAmount, l.creditAmount])).toEqual([
      ['cash', '0', '100.0000'],
      ['sales', '100.0000', '0'],
    ]);
    expect(created[0]!.lines[0]).toMatchObject({ partyType: 'customer', partyId: 'c1' });
    expect(created[0]!.idempotencyKey).toBe('reversal-m1');
  });

  it('2. only once, never a reversal of a reversal, never a draft', async () => {
    const { reversal } = await service.reverseManual('m1', { reason: 'x' });
    await expect(service.reverseManual('m1', { reason: 'x' })).rejects.toThrow(/اتعكس قبل كده/);
    await expect(service.reverseManual(reversal.id, { reason: 'x' })).rejects.toThrow(/قيد عكسي/);
    await expect(service.reverseManual('draft', { reason: 'x' })).rejects.toThrow(
      /only a posted entry/,
    );
  });

  it('3. a document entry cannot be reversed by hand — only through its document', async () => {
    await expect(service.reverseManual('auto', { reason: 'x' })).rejects.toThrow(
      /تابع لمستند \(sales_invoice SI-1\)/,
    );
    const done = await service.reverseForSource('sales_invoice', 'SI-1', 'invoice cancelled');
    expect(done).toHaveLength(1);
    expect(await service.reverseForSource('sales_invoice', 'SI-1', 'again')).toHaveLength(0);
  });
});
