import { Injectable } from '@nestjs/common';
import { AccountingNotFoundError, AccountingValidationError } from './accounting.errors';
import { AccountingRepository } from './accounting.repository';
import { AccountingService } from './accounting.service';
import type { JournalEntryRecord } from './accounting.types';

export interface ReversalResult { original: JournalEntryRecord; reversal: JournalEntryRecord; }

/**
 * Plan item 31 — posted entries are frozen: never edited, never cancelled on their own.
 * A manual entry is corrected by one mirror entry (debits ↔ credits) linked back to it; an entry
 * produced by a source document is reversed only through that document (reverseForSource).
 */
@Injectable()
export class JournalReversalService {
  constructor(private readonly accounting: AccountingService, private readonly repository: AccountingRepository) {}

  /** Manual (hand-made) entries only. */
  async reverseManual(id: string, input: { reason: string; reversalDate?: string }): Promise<ReversalResult> {
    const entry = await this.mustFind(id);
    if (entry.isAutoGenerated || (entry.sourceEventType && entry.sourceEventType !== 'reversal')) {
      throw new AccountingValidationError(
        `القيد ${entry.entryNumber} تابع لمستند (${entry.sourceEventType ?? 'auto'} ${entry.reference ?? ''}) — بيتعكس لما المستند نفسه يتلغي، مش من هنا`,
      );
    }
    return this.reverse(entry, input.reason, input.reversalDate);
  }

  /** For source modules cancelling a posted document: reverses every posted entry it produced. */
  async reverseForSource(sourceEventType: string, reference: string, reason: string, reversalDate?: string): Promise<ReversalResult[]> {
    const out: ReversalResult[] = [];
    for (const id of await this.repository.listPostedEntryIdsBySource(sourceEventType, reference)) {
      const links = await this.repository.findReversalLinks(id);
      if (links.reversedById) continue; // already reversed — idempotent
      out.push(await this.reverse(await this.mustFind(id), reason, reversalDate));
    }
    return out;
  }

  async links(id: string): Promise<{ reversedById: string | null; reversalOfId: string | null; reason: string | null }> {
    await this.mustFind(id);
    return this.repository.findReversalLinks(id);
  }

  private async reverse(entry: JournalEntryRecord, reason: string, reversalDate?: string): Promise<ReversalResult> {
    if (!reason?.trim()) throw new AccountingValidationError('a reason is required to reverse a journal entry');
    if (entry.status !== 'posted') throw new AccountingValidationError(`only a posted entry can be reversed (entry ${entry.entryNumber} is "${entry.status}")`);
    const links = await this.repository.findReversalLinks(entry.id);
    if (links.reversalOfId) throw new AccountingValidationError(`القيد ${entry.entryNumber} هو نفسه قيد عكسي — مينفعش يتعكس`);
    if (links.reversedById) throw new AccountingValidationError(`القيد ${entry.entryNumber} اتعكس قبل كده`);
    if (!entry.orgNodeId) throw new AccountingValidationError(`journal entry ${entry.entryNumber} has no company`);
    const draft = await this.accounting.createEntry({
      orgNodeId: entry.orgNodeId,
      description: `[عكس] ${entry.entryNumber}: ${reason.trim()}`,
      reference: entry.reference ?? entry.entryNumber,
      entryDate: reversalDate,
      idempotencyKey: `reversal-${entry.id}`,
      sourceEventType: 'reversal',
      lines: entry.lines.map((l) => ({
        accountId: l.accountId, debitAmount: l.creditAmount, creditAmount: l.debitAmount,
        description: `[عكس] ${l.description ?? ''}`.trim(),
        partyType: (l.partyType as 'customer' | 'supplier' | null) ?? undefined, partyId: l.partyId ?? undefined,
        costCenterId: l.costCenterId ?? undefined, jobOrderId: l.jobOrderId ?? undefined,
      })),
    });
    await this.repository.markReversal(draft.id, entry.id, reason.trim());
    const reversal = await this.accounting.postEntry(draft.id);
    return { original: entry, reversal };
  }

  private async mustFind(id: string): Promise<JournalEntryRecord> {
    const e = await this.repository.findEntryById(id);
    if (!e) throw new AccountingNotFoundError(`journal entry ${id} does not exist`);
    return e;
  }
}
