import { AccountingValidationError } from './accounting.errors';
import type { AccountingService } from './accounting.service';
import type { CreateJournalLineInput, JournalEntryRecord } from './accounting.types';

/**
 * Posts a document's journal entry through AccountingService (the same path every other document
 * uses: account, period, cost-center and budget checks, then posting). Used by the tax / customs
 * and accruals services, which used to call a posting-engine method that never existed.
 */
export interface ManualJournalLine {
  accountId: string;
  debit: number;
  credit: number;
  description?: string;
}
export interface ManualJournalInput {
  orgNodeId: string;
  entryDate: string;
  description: string;
  reference: string;
  /** Source document type, e.g. "vat_settlement"; with `idempotencyKey` it makes a retry safe. */
  sourceEventType: string;
  idempotencyKey: string;
  lines: ManualJournalLine[];
}

const r4 = (n: number): number => Math.round(n * 10000) / 10000;

export async function postManualJournal(
  accounting: AccountingService,
  input: ManualJournalInput,
): Promise<JournalEntryRecord> {
  const lines: CreateJournalLineInput[] = input.lines
    .map((l) => ({ ...l, debit: r4(l.debit), credit: r4(l.credit) }))
    .filter((l) => l.debit > 0 || l.credit > 0)
    .map((l) => ({
      accountId: l.accountId,
      debitAmount: l.debit.toFixed(4),
      creditAmount: l.credit.toFixed(4),
      description: l.description,
    }));
  const debit = lines.reduce((s, l) => s + Number(l.debitAmount), 0);
  const credit = lines.reduce((s, l) => s + Number(l.creditAmount), 0);
  if (lines.length < 2 || Math.abs(debit - credit) > 0.00005)
    throw new AccountingValidationError(
      `قيد ${input.reference} مش متوازن (مدين ${debit.toFixed(4)} / دائن ${credit.toFixed(4)})`,
    );
  const existing = await accounting.findEntryByIdempotencyKey(input.idempotencyKey);
  if (existing) return existing.status === 'posted' ? existing : accounting.postEntry(existing.id);
  const draft = await accounting.createEntry({
    orgNodeId: input.orgNodeId,
    description: input.description,
    reference: input.reference,
    entryDate: input.entryDate,
    isAutoGenerated: true,
    idempotencyKey: input.idempotencyKey,
    sourceEventType: input.sourceEventType,
    lines,
  });
  return draft.status === 'posted' ? draft : accounting.postEntry(draft.id);
}
