import { PostingEngineService } from './posting-engine.service';
import { AccountingService } from './accounting.service';
import { AccountingRepository } from './accounting.repository';
import type {
  AccountDeterminationRecord,
  CompanyAccountingConfigRecord,
  JournalEntryRecord,
} from './accounting.types';
import type { StockMovementPostingPayload } from './posting-engine.types';

describe('PostingEngineService — Automated Financial Posting Engine', () => {
  let postingEngine: PostingEngineService;
  let accountingRepo: AccountingRepository;
  let accountingService: AccountingService;

  // Mock In-Memory State
  let postedEntries: Map<string, JournalEntryRecord> = new Map();
  let idempotencyMap: Map<string, JournalEntryRecord> = new Map();

  const mockOrgNodeId = 'org-company-1';
  const mockWarehouseId = 'wh-raw-materials';
  const mockInvAccountId = 'acc-raw-materials-asset';
  const mockGrniAccountId = 'acc-grni-liability';
  const mockWipAccountId = 'acc-wip-asset';
  const mockCogsAccountId = 'acc-cogs-expense';

  beforeEach(() => {
    postedEntries = new Map();
    idempotencyMap = new Map();

    accountingRepo = {
      findCompanyConfig: jest.fn().mockResolvedValue({
        orgNodeId: mockOrgNodeId,
        defaultGrniAccountId: mockGrniAccountId,
        defaultWipAccountId: mockWipAccountId,
        defaultCogsAccountId: mockCogsAccountId,
      } as CompanyAccountingConfigRecord),
      listAccountDeterminations: jest.fn().mockResolvedValue([
        {
          orgNodeId: mockOrgNodeId,
          determinationType: 'warehouse',
          referenceId: mockWarehouseId,
          accountPurpose: 'inventory',
          accountId: mockInvAccountId,
        } as AccountDeterminationRecord,
      ]),
      findEntryByIdempotencyKey: jest.fn().mockImplementation(async (key: string) => {
        return idempotencyMap.get(key) ?? null;
      }),
    } as unknown as AccountingRepository;

    accountingService = {
      createEntry: jest.fn().mockImplementation(async (input) => {
        const id = `je-${postedEntries.size + 1}`;
        const record: JournalEntryRecord = {
          id,
          entryNumber: `JE-2026-00000${postedEntries.size + 1}`,
          orgNodeId: input.orgNodeId,
          reference: input.reference ?? null,
          description: input.description,
          entryDate: input.entryDate ?? new Date().toISOString(),
          postedAt: null,
          status: 'draft',
          fiscalYearId: input.fiscalYearId ?? null,
          periodId: input.periodId ?? null,
          isAutoGenerated: input.isAutoGenerated ?? false,
          idempotencyKey: input.idempotencyKey ?? null,
          sourceEventType: input.sourceEventType ?? null,
          lines: input.lines.map((l: any, idx: number) => ({
            id: `jl-${idx + 1}`,
            journalEntryId: id,
            accountId: l.accountId,
            debitAmount: l.debitAmount ?? '0',
            creditAmount: l.creditAmount ?? '0',
            description: l.description ?? null,
            costCenterId: l.costCenterId ?? null,
            jobOrderId: l.jobOrderId ?? null,
          })),
        };
        postedEntries.set(id, record);
        if (input.idempotencyKey) {
          idempotencyMap.set(input.idempotencyKey, record);
        }
        return record;
      }),
      postEntry: jest.fn().mockImplementation(async (id: string) => {
        const entry = postedEntries.get(id);
        if (!entry) throw new Error('Not found');
        entry.status = 'posted';
        entry.postedAt = new Date().toISOString();
        return entry;
      }),
    } as unknown as AccountingService;

    postingEngine = new PostingEngineService(accountingRepo, accountingService);
  });

  it('1. Purchase Receipt: should automatically generate and post [Dr Inventory Asset / Cr GRNI]', async () => {
    const payload: StockMovementPostingPayload = {
      movementId: 'mov-receipt-1',
      itemId: 'item-sheet-metal',
      warehouseId: mockWarehouseId,
      orgNodeId: mockOrgNodeId,
      movementType: 'receipt',
      quantity: '50',
      unitCost: '100.000000',
      totalValue: '5000.0000',
      note: 'PO-2026-001 receipt',
    };

    const entry = await postingEngine.postStockMovement(payload);

    expect(entry).not.toBeNull();
    expect(entry?.status).toBe('posted');
    expect(entry?.isAutoGenerated).toBe(true);
    expect(entry?.idempotencyKey).toBe('stock-movement-mov-receipt-1');
    expect(entry?.lines.length).toBe(2);

    // Dr Inventory Asset
    const drLine = entry?.lines.find((l) => l.accountId === mockInvAccountId);
    expect(drLine?.debitAmount).toBe('5000.0000');
    expect(drLine?.creditAmount).toBe('0');

    // Cr GRNI
    const crLine = entry?.lines.find((l) => l.accountId === mockGrniAccountId);
    expect(crLine?.debitAmount).toBe('0');
    expect(crLine?.creditAmount).toBe('5000.0000');
  });

  it('2. Manufacturing Issue: should automatically generate and post [Dr WIP / Cr Inventory Asset]', async () => {
    const payload: StockMovementPostingPayload = {
      movementId: 'mov-issue-mfg-1',
      itemId: 'item-sheet-metal',
      warehouseId: mockWarehouseId,
      orgNodeId: mockOrgNodeId,
      movementType: 'issue',
      quantity: '10',
      unitCost: '100.000000',
      totalValue: '1000.0000',
      sourceModule: 'production',
      sourceId: 'wo-2026-001',
      note: 'Issue to Work Order WO-001',
    };

    const entry = await postingEngine.postStockMovement(payload);

    expect(entry).not.toBeNull();
    expect(entry?.status).toBe('posted');

    // Dr WIP
    const drLine = entry?.lines.find((l) => l.accountId === mockWipAccountId);
    expect(drLine?.debitAmount).toBe('1000.0000');
    expect(drLine?.creditAmount).toBe('0');

    // Cr Inventory Asset
    const crLine = entry?.lines.find((l) => l.accountId === mockInvAccountId);
    expect(crLine?.debitAmount).toBe('0');
    expect(crLine?.creditAmount).toBe('1000.0000');
  });

  it('3. Sales Delivery Issue: should automatically generate and post [Dr COGS / Cr Inventory Asset]', async () => {
    const payload: StockMovementPostingPayload = {
      movementId: 'mov-delivery-1',
      itemId: 'item-sheet-metal',
      warehouseId: mockWarehouseId,
      orgNodeId: mockOrgNodeId,
      movementType: 'issue',
      quantity: '5',
      unitCost: '100.000000',
      totalValue: '5000.0000',
      sourceModule: 'delivery',
      sourceId: 'dn-2026-001',
      note: 'Delivery note DN-001',
    };

    const entry = await postingEngine.postStockMovement(payload);

    expect(entry).not.toBeNull();

    // Dr COGS
    const drLine = entry?.lines.find((l) => l.accountId === mockCogsAccountId);
    expect(drLine?.debitAmount).toBe('5000.0000');

    // Cr Inventory Asset
    const crLine = entry?.lines.find((l) => l.accountId === mockInvAccountId);
    expect(crLine?.creditAmount).toBe('5000.0000');
  });

  it('4. Idempotency: Duplicate calls must return the existing journal entry without creating new ones', async () => {
    const payload: StockMovementPostingPayload = {
      movementId: 'mov-duplicate-test',
      itemId: 'item-1',
      warehouseId: mockWarehouseId,
      orgNodeId: mockOrgNodeId,
      movementType: 'receipt',
      quantity: '10',
      unitCost: '50.000000',
      totalValue: '500.0000',
    };

    // First call
    const firstEntry = await postingEngine.postStockMovement(payload);
    expect(firstEntry).not.toBeNull();

    // Second call with the same payload
    const secondEntry = await postingEngine.postStockMovement(payload);

    expect(secondEntry?.id).toBe(firstEntry?.id);
    expect(accountingService.createEntry).toHaveBeenCalledTimes(1);
    expect(accountingService.postEntry).toHaveBeenCalledTimes(1);
  });

  it('5. Graceful Fallback: Should safely return null when accounts are not configured', async () => {
    // Unmapped warehouse / company
    (accountingRepo.listAccountDeterminations as jest.Mock).mockResolvedValueOnce([]);
    (accountingRepo.findCompanyConfig as jest.Mock).mockResolvedValueOnce(null);

    const payload: StockMovementPostingPayload = {
      movementId: 'mov-unmapped',
      itemId: 'item-unmapped',
      warehouseId: 'wh-unmapped',
      orgNodeId: 'org-unmapped',
      movementType: 'receipt',
      quantity: '10',
      unitCost: '50.000000',
      totalValue: '500.0000',
    };

    const result = await postingEngine.postStockMovement(payload);
    expect(result).toBeNull();
    expect(accountingService.createEntry).not.toHaveBeenCalled();
  });
});
